# GAME_V2_CLIENT_CONFIG_V1
client_id=jzg37
node_country=nl
server_endpoint=91.223.119.134
wireguard_port=51874
server_speederv2_port=40974
client_speederv2_port=30974
server_wg_address=10.77.4.1/30
client_wg_address=10.77.4.2/30
route_cidr=192.168.3.0/24
route_table=51874
wan_iface=wan
mtu=1500
