(async()=>{

'use strict';
const boot=JSON.parse(document.querySelector('#boot-data').textContent), C=WorkbenchCore, policy=boot.policy, DATA=boot.runs, ACQ=boot.acquisitions||{items:[],batches:[]};
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arr=v=>v==null?[]:Array.isArray(v)?v:[v];
const icon=(name)=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${({home:'<path d="m3 10 9-7 9 7v10H3Z"/><path d="M9 20v-7h6v7"/>',search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',alert:'<circle cx="12" cy="12" r="9"/><path d="M12 7v6m0 3v.2"/>',file:'<path d="M5 3h9l5 5v13H5Z"/><path d="M14 3v6h5M8 13h8m-8 4h6"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',check:'<path d="m5 12 4 4L19 6"/>',back:'<path d="M20 12H4m6-6-6 6 6 6"/>'})[name]||''}</svg>`;
const label={full_text:'已取得全文',revise:'修正',exclude:'排除',abstract_only:'仅摘要',abstract:'仅摘要',official_record:'官方记录',official_guidance:'官方指导',guidance:'专业指导',narrative_review:'叙述性综述',professional_patient_guidance:'专业患者指导',public_health_guidance:'公共健康指导',human_study:'人体研究',original_research:'原始研究',mechanistic_study:'机制研究',partial:'覆盖不全',missing:'缺证据',covered:'已覆盖',blocked:'未通过',unknown:'待核验',unavailable:'未取得',unassessed:'待评估',frozen:'已冻结',historical:'历史版本',invalidated:'已失效',review:'分支审阅',direction:'方向选择',package:'研究包',support:'支持',counter:'反向线索',counterevidence:'反向线索',limitation:'局限',gap:'保留待补证',keep:'保留',reject:'不采用',adjust:'调整表达',primary:'主方向草案',secondary:'补充草案',supplemental:'补充草案',background:'背景资料',trial_only:'试运行草案',onset:'发生时间',duration:'持续时间',recovery:'恢复时间',progression:'变化过程',missing_reason:'尚缺信息',amplifiers:'加重因素',mitigators:'缓解因素',context:'适用场景',scope:'适用范围',claim_ids:'关联主张',source_ids:'关联来源',note:'说明',assessment:'评估说明',method:'研究方法',independence:'独立性',source_quality:'来源质量',author_fit:'作者适配性',score:'分数',status:'状态',population_limits:'人群限制',publisher_identity:'发布机构',method_basis:'方法依据',limitations:'局限',key_conclusion_eligibility:'关键结论适用性',affiliation_country:'机构所在国',study_population_countries:'研究人群地区'};
const L=v=>label[v]||v||'未记录';
function textValue(v){if(v==null)return '<span class="muted">未记录／待核验</span>';if(Array.isArray(v))return v.length?`<ul class="text-list">${v.map(x=>`<li>${textValue(x)}</li>`).join('')}</ul>`:'<span class="muted">暂无记录</span>';if(typeof v==='object')return `<dl class="details-list">${Object.entries(v).filter(([,x])=>x!==undefined).map(([k,x])=>`<div><dt>${esc(L(k))}</dt><dd>${textValue(x)}</dd></div>`).join('')}</dl>`;return esc(v)}
const tag=(t,c='')=>`<span class="tag ${c}">${esc(t)}</span>`;
const sections=[['home','任务总览',''],['scope','任务设定','01'],['evidence','证据材料','02'],['review','分支审阅','03'],['directions','方向与补证','04'],['delivery','研究交付','05']];
const pageHelpContent={
  home:{purpose:'看清这项研究做到哪、卡在哪，找到下一步。',action:'先确认顶部选中的任务，再看“建议下一步”。新任务从“任务设定”开始，旧任务接着未完成的环节往下做。',role:'串起定范围、查材料、审判断、选方向与补证、交研究包的顺序。',example:'看到“平台兴趣待核验”，就去“方向与补证”看还缺哪些可核验的记录。'},
  scope:{purpose:'先把研究问题说清楚，避免后面越查越散。',action:'确认主题、研究模式、最想回答的问题和不做的范围，再看适用人群与产品角色是否合适。',role:'给后续查资料和分析分支划定范围，明确这次需要回答什么。',example:'“熬夜会带来哪些变化？”从行为出发；“皮肤干燥有哪些可能原因？”从结果出发。',note:'新建任务会校验必填范围；创建成功后仍需导出任务交给 Codex 取证。'},
  evidence:{purpose:'看每条判断凭什么成立，哪些地方还不确定。',action:'在“获取成果”阅读论文正文或视频字幕；在“平台线索”看补取进展。打开详情核对来源、获取时间和局限。',role:'为分支判断提供依据。平台热度只说明关注度，不能证明护肤效果。',example:'查看“熬夜与肤况”的资料时，先核对研究了谁、观察了什么，别只看标题。'},
  review:{purpose:'把一个大问题拆成几条解释，逐条确认哪些有依据、哪些要修改。',action:'选一支，依次看判断、证据和边界；记录保留、调整、不采用或待补证的意见，并写下理由。',role:'把材料变成你审过的判断，再提炼内容方向。关键异议没解决，先别定正式方向。',example:'“这项资料只研究成年人，表达时要保留人群限制。”',note:'先逐支填写待提交意见，再点“提交全部审阅”登记身份。提交后可冻结本版审阅；刷新前请保存或导出。'},
  directions:{purpose:'从审过的判断中挑选本期值得讲的问题，列出还要查什么。',action:'先看方向的科学依据和平台兴趣；有缺口就切到“待补证”，每次选 1–2 项查看要求，按预算逐目标导出补证请求。',role:'连接专业审阅与最终研究包。证据和兴趣都核验通过后，再确认本期方向；补证围绕具体问题进行。',example:'有科学依据，但缺平台兴趣记录：先补记录，别把“尚不清楚”写成“没人关心”。',note:'请求导出前检查原任务剩余额度；导出不代表执行，也不会关闭缺口。'},
  delivery:{purpose:'把选定方向的判断、证据和边界，整理成一份可以独立阅读、继续使用的研究包。',action:'检查结论有没有说过头、来源能否追溯、缺口是否写清，再查看完整研究包和历史版本。',role:'交付本轮研究结果，为后续内容创作提供依据。包已生成，不代表其中的缺口已经解决。',example:'拿到研究包，应能说清“讲什么、凭什么、适用于谁、哪些还不知道”。'}
};
let active=0,busy=false,initialized=false;
const freshState=d=>({view:'home',branch:d.branches[0]?.id,branchTab:'overview',evidenceTab:'sources',directionTab:'candidates',candidate:d.candidates[0]?.id,deliveryTab:'summary',query:'',sourceFilter:'all',page:1,gapPage:1,gapQuery:'',gapFilter:'all',versionPage:1,selected:new Set(),drafts:{},dirty:false});
const states=DATA.map(freshState), D=()=>DATA[active], S=()=>states[active], T=()=>C.taskFor(D(),policy), gaps=()=>D().gaps.filter(g=>g.status!=='closed'),byId=(key,id)=>(D()[key]||[]).find(x=>x.id===id);
const taskShort=d=>C.taskFor(d,policy)?.topic||d.run_id;
const tabs=(key,items,value)=>`<div class="tabs" role="tablist" aria-label="当前工作区内容">${items.map(([id,title,count])=>`<button role="tab" id="tab-${key}-${id}" aria-controls="panel-${key}" aria-selected="${value===id}" tabindex="${value===id?'0':'-1'}" data-tab="${key}" data-value="${id}">${title}${count==null?'':`<span class="count">${count}</span>`}</button>`).join('')}</div>`;
const heading=(title,desc,action='')=>`<div class="page-heading"><div class="page-heading-copy"><h1>${title}</h1><p>${desc}</p></div><div class="page-heading-actions">${action}<button class="help-trigger" data-action="page-help" aria-haspopup="dialog" aria-controls="dialog"><svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v.2"/></svg><span>使用帮助</span></button></div></div>`;
const goButton=(v,t,primary=false,tab='')=>`<button ${primary?'class="primary"':''} data-go="${v}" ${tab?`data-open-tab="${tab}"`:''}>${t}${primary?icon('arrow'):''}</button>`;
function pager(total,page,key){const last=Math.max(1,Math.ceil(total/5));return `<div class="pagination"><span>${total?`${(page-1)*5+1}–${Math.min(page*5,total)} / ${total} 条`:'0 条'} · 每页 5 条</span><div class="row"><button data-page="${key}" data-delta="-1" ${page<=1?'disabled':''} aria-label="上一页">上一页</button><span class="page-number" aria-label="第 ${page} 页，共 ${last} 页">${page} / ${last}</span><button data-page="${key}" data-delta="1" ${page>=last?'disabled':''} aria-label="下一页">下一页</button></div></div>`}
function refs(key,ids,prefix=''){return `<div class="ref-row">${arr(ids).map(id=>byId(key,id)?`<button class="ref" data-detail="${key}" data-id="${esc(id)}">${prefix}${esc(id.split('-').slice(-1)[0])} ↗</button>`:'').join('')}</div>`}
function render(){const d=D(),s=S();if(!d)return;$('#save-state').textContent=s.dirty?'有改动 · 请保存或导出':'已载入 · 本地文件';$('#task-switch').innerHTML=DATA.map((x,i)=>`<option value="${i}" ${i===active?'selected':''}>${taskShort(x)} · ${x.mode==='behavior'?'行为型':'结果型'}</option>`).join('');$('#nav').innerHTML=sections.map(([id,title,num],i)=>`${i===1?'<div class="nav-group">研究流程</div>':''}<button class="nav-btn" ${s.view===id?'aria-current="page"':''} data-go="${id}">${num?`<span class="nav-num">${num}</span>`:icon('home')}<span>${title}</span>${id==='directions'?`<span class="nav-count" aria-label="${gaps().length} 项未关闭缺口">${gaps().length}</span>`:''}</button>`).join('');$('#content').innerHTML=({home:home,scope:scope,evidence:evidence,review:review,directions:directions,delivery:delivery}[s.view])();document.title=`${sections.find(x=>x[0]===s.view)[1]} · 护肤研究 工作台`;}
function navigate(view,tab){S().view=view;if(tab&&view==='directions')S().directionTab=tab;if(tab&&view==='delivery')S().deliveryTab=tab;if(tab&&view==='evidence'){S().evidenceTab=tab;S().page=1;S().query=''}closeMenu();render();$('#content').focus({preventScroll:true})}
function home(){
 const d=D(),empty=!d.sources.length,dir=C.latest(d,'direction'),pack=C.latest(d,'package'),candidate=byId('candidates',dir?.content.selection.candidate_id)||d.candidates[0],g=candidate?C.gates(d,candidate,policy):null,acq=acquisitions();
 return heading('任务总览','从当前卡点继续，也可以按左侧顺序查看整项研究。','<button data-action="new-task">＋ 新建任务</button>')+`<div class="page-scroll"><div class="task-banner"><div><div class="eyebrow">当前任务 <span class="mono"> / ${esc(d.run_id)}</span></div><h2>${esc(T().topic)}</h2><div class="row wrap">${tag(d.mode==='behavior'?'行为型研究':'结果型研究','blue')}${tag(pack?pack.classification==='formal'?'正式研究包已冻结':'试运行包已冻结':empty?'已设定 · 待取证':dir?'方向已冻结':'含缺口 · 待继续审阅','warn')}<span class="small muted">${esc(d.revision)}</span></div></div></div><div class="home-grid"><section class="next-action"><span class="eyebrow">建议下一步</span><span class="index">NEXT</span><h2>${empty?'范围已设定，<br>下一步收集证据。':gaps().length?'先明确待补证项，<br>再推进候选方向。':'核对判断与边界，<br>再确认研究交付。'}</h2><p>${empty?'导出任务 JSON，交给 Codex 按绑定范围和预算取证。页面不会自动联网搜索。':`当前仍有 ${gaps().length} 项未关闭缺口。获取到正文不代表科学审核通过，平台兴趣也需独立核验。`}</p><div class="btn-row">${empty?'<button class="primary" data-action="export-json">导出任务 JSON ↓</button>':goButton('directions','查看待补证项',true,'gaps')}<button class="linkbtn" data-go="review">查看分支判断 →</button></div></section><section class="surface compact-block"><div class="row between"><h3>当前材料与判断</h3>${tag(g?.formal?'门槛已通过':'尚有待核验项','warn')}</div><div class="issue">${icon('alert')}<div><h3>科学证据：${g?.science.pass?'通过':'尚未通过'}</h3><p>核对来源质量、分支覆盖与适用边界。</p></div></div><div class="issue">${icon('alert')}<div><h3>平台兴趣：${g?.interest.pass?'通过':'尚未通过'}</h3><p>需要原页日期、可见指标和可比依据。</p></div></div><div class="stats-row"><div class="stat"><strong>${d.sources.length}</strong><span>科学来源</span></div><div class="stat"><strong>${d.branches.length}</strong><span>研究分支</span></div><div class="stat"><strong>${d.candidates.length}</strong><span>方向记录</span></div></div>${acq.length?`<button class="linkbtn small" data-go="evidence" data-open-tab="acquisitions">查看获取成果 · ${esc(acquisitionSummary(acq))} →</button>`:goButton('evidence','查阅已有材料')}</section></div><section class="home-foot"><div class="row between"><h3>这项研究怎么使用</h3><span class="small muted">随时切换，不必从头重来</span></div><div class="flow">${[['scope','确定范围','已设定'],['evidence','查阅材料',`${d.sources.length} 份来源`],['review','逐支判断',C.latest(d,'review')?'已冻结':'待确认'],['directions','方向与补证',dir?'已冻结':`${gaps().length} 项待补`],['delivery','查看研究包',pack?'已冻结':'待确认']].map(([v,t,st],i)=>`<button class="flow-step ${i===3&&!empty?'current':''}" data-go="${v}"><span class="step">0${i+1}</span><strong>${t}</strong><small>${st}</small></button>`).join('')}</div></section></div>`;
}
function scope(){const d=D();return heading('任务设定','先明确研究什么，以及哪些结论不在本次范围。',`<button data-action="new-task">＋ 新建任务</button>`)+`<div class="page-scroll"><div class="scope-grid"><section class="surface pad"><div class="row between"><h3>研究范围</h3>${tag('现有任务 · 只读')}</div><dl class="details-list"><div><dt>研究主题</dt><dd>${esc(T().topic)}</dd></div><div><dt>研究模式</dt><dd>${d.mode==='behavior'?'行为型 · 从行为出发，追问影响与可改变因素':'结果型 · 从表象出发，区分原因、边界与护理顺序'}</dd></div><div><dt>这次希望回答</dt><dd>${esc(T().objective)}</dd></div><div><dt>适用人群</dt><dd>一般成年人 · 日常护肤科普 · 非个体诊疗</dd></div><div><dt>产品角色</dt><dd>${esc(T().product_role)}</dd></div></dl></section><section class="surface pad"><h3>先围绕这几个问题</h3><ol class="step-list">${T().core_questions.map(q=>`<li>${esc(q)}</li>`).join('')}</ol><hr class="rule"><div class="section-label">明确不做</div>${textValue(T().exclude)}<div class="note mt">本页展示任务范围；绑定策略和剩余额度可在下方查看。</div></section></div><div class="btn-row mt">${goButton('evidence','下一步：查阅证据',true)}<button data-action="policy">策略与预算记录</button></div></div>`}
function evidence(){
 const d=D(),s=S(),tab=s.evidenceTab,acq=acquisitions(),items=[['sources','科学来源',d.sources.length],['acquisitions','获取成果',acq.length],['claims','研究主张',d.claims.length],['signals','平台线索',d.signals.length],['knowledge','知识库对照',null]];
 let html=heading('证据材料','查原有证据，也能直接阅读工具实际获取的内容。')+tabs('evidenceTab',items,tab);
 if(tab==='knowledge'){const kb=d.knowledge_base||{};return html+`<div class="page-scroll surface pad" role="tabpanel" id="panel-evidenceTab" aria-labelledby="tab-evidenceTab-knowledge"><h2>本轮知识库对照</h2><div class="note mt">这里只展示本轮实际查询结果；未匹配不代表整个知识库没有相关知识。不会自动写入知识库。</div>${textValue(kb)}</div>`}
 const query=s.query.trim().toLowerCase(),input=tab==='acquisitions'?[...acq].sort((a,b)=>Number(Boolean(b.video?.content_analysis?.overview))-Number(Boolean(a.video?.content_analysis?.overview))):d[tab];
 const all=input.filter(x=>JSON.stringify(x).toLowerCase().includes(query)).filter(x=>tab!=='sources'||s.sourceFilter==='all'||s.sourceFilter==='pubmed'&&sourceHost(x)==='pubmed.ncbi.nlm.nih.gov'||s.sourceFilter==='mcp'&&acq.some(a=>a.source_id===x.id));
 const total=all.length;s.page=Math.min(s.page,Math.max(1,Math.ceil(total/5)));
 html+=`<div class="page-body" role="tabpanel" id="panel-evidenceTab" aria-labelledby="tab-evidenceTab-${tab}"><div class="toolbar"><div class="searchbox">${icon('search')}<input id="material-search" data-input="query" type="search" aria-label="搜索当前材料" placeholder="搜索标题、关键词或资料编号" value="${esc(s.query)}"></div>${tab==='sources'?`<select id="source-filter" aria-label="筛选来源渠道"><option value="all" ${s.sourceFilter==='all'?'selected':''}>全部渠道</option><option value="pubmed" ${s.sourceFilter==='pubmed'?'selected':''}>PubMed 条目</option><option value="mcp" ${s.sourceFilter==='mcp'?'selected':''}>PubMed MCP 补取记录</option></select>`:`<span class="small muted">${tab==='signals'?'平台线索不等于兴趣已验证':tab==='acquisitions'?'按顶部所选研究任务展示':'每次打开一条详情'}</span>`}</div><div class="table-wrap">${tab==='acquisitions'?`<div class="note">${esc(acquisitionSummary(acq))}。均为已有资料补取；获取成功不等于质量审核或兴趣门槛通过。</div>`:''}<div class="list-header"><span>${items.find(x=>x[0]===tab)[1]}</span><span>状态 / 操作</span></div>${total?all.slice((s.page-1)*5,s.page*5).map(x=>materialRow(x,tab)).join(''):`<div class="empty"><strong>没有匹配的材料</strong><p>当前任务可能尚无此类记录，或需要调整搜索与筛选。</p><button class="mt" data-action="clear-search">清除搜索与筛选</button></div>`}</div>${pager(total,s.page,'page')}</div>`;
 return html;
}
function materialRow(x,key){
 const acquisition=key==='acquisitions',latest=key==='signals'?signalAcquisition(x):null,title=x.title||x.text||x.indexed_title||`${x.platform} 平台线索`,summary=acquisition?x.result_summary:latest?latest.result_summary:x.excerpt_or_summary||x.allowed_expression||x.missing_reason||'',status=acquisition?acquisitionStatus(x):key==='sources'?L(x.read_level):key==='signals'?latest?'已补取 · 兴趣待核验':'兴趣待核验':'需限定表达';
 const overview=acquisition&&x.kind==='video'?x.video.content_analysis?.overview:null;
 return `<article class="data-row${overview?' has-video-summary':''}"><div class="grow"><div class="meta"><span class="mono muted">${esc(x.id)}</span>${tag(status,acquisition||key==='signals'?'blue':'')}</div><h3><button class="linkbtn" data-detail="${key}" data-id="${esc(x.id)}">${esc(title)}</button></h3>${overview?`<section class="acquisition-summary" aria-label="视频中文摘要"><strong>中文摘要</strong><p>${esc(overview)}</p><small>根据英文自动字幕整理</small></section>`:`<p class="description clamp">${esc(arr(summary).join('；'))}</p>`}${key==='sources'?sourceBadges(x):acquisition?`<div class="provenance">${tag(x.channel)}${tag('已有资料补取')}${tag(acquisitionBatch(x).acquired_on)}</div>`:latest?`<div class="provenance">${tag('YouTube · 英文自动字幕')}${tag(acquisitionBatch(latest).acquired_on)}</div>`:''}</div><div class="trailing"><button class="linkbtn small" data-detail="${key}" data-id="${esc(x.id)}">${overview?'查看观点与字幕':acquisition&&x.status==='retrieved'?'阅读获取内容':'查看详情'} ↗</button></div></article>`;
}
function branchChoices(){const d=D(),s=S();return `<div class="branch-list" aria-label="选择研究分支">${d.branches.map((b,i)=>`<button class="branch-item" aria-pressed="${s.branch===b.id}" data-branch="${esc(b.id)}"><span class="mono muted">分支 0${i+1}</span><h3>${esc(b.title)}</h3><div class="row between">${tag(s.drafts[b.id]?'意见待提交':C.review(d,b.id)?L(C.review(d,b.id).action):'等待审阅',s.drafts[b.id]?'blue':'warn')}<span class="small muted">${b.source_ids.length} 来源</span></div></button>`).join('')}</div>`}
function review(){
 const b=byId('branches',S().branch)||D().branches[0],s=S();
 let h=heading('分支审阅','逐支填写意见，提交全部后可冻结本版审阅。',`<div class="operation-bar"><button data-action="submit-reviews" ${D().branches.length?'':'disabled'}>提交全部审阅</button><button data-action="freeze-review" ${C.allReviewed(D())&&!Object.keys(s.drafts).length?'':'disabled'}>冻结审阅</button></div>`);
 if(!b)return h+'<div class="empty"><strong>尚无研究分支</strong><p>先取得材料并导入研究记录，再进行审阅。</p></div>';
 s.branch=b.id;
 return h+`<div class="split">${branchChoices()}<article class="detail"><div class="detail-head"><div class="row between"><span class="mono muted">${esc(b.id)}</span>${tag(L(b.coverage),'warn')}</div><h2>${esc(b.title)}</h2>${tabs('branchTab',[['overview','判断概览'],['claims','主张与证据'],['bounds','适用边界'],['records','审阅记录']],s.branchTab)}</div><div class="detail-scroll" role="tabpanel" id="panel-branchTab" aria-labelledby="tab-branchTab-${s.branchTab}">${branchContent(b)}</div><footer class="detail-foot"><span class="muted small">${s.drafts[b.id]?'有待提交意见 · 刷新前请提交并保存':C.latest(D(),'review')?'本版审阅已冻结':C.review(D(),b.id)?'本支意见已记录':'本支等待本版审阅'}</span><button class="primary" data-action="review-form">填写审阅意见 ${icon('arrow')}</button></footer></article></div>`;
}
function branchContent(b){const tab=S().branchTab;if(tab==='overview')return `<div class="judgment"><h3>当前判断</h3><p>${esc(b.preliminary_judgment)}</p></div><section class="subsection"><h3>这一支研究什么</h3><p class="prose">${esc(b.definition)}</p></section><section class="subsection"><h3>为什么放在这个位置</h3><p class="prose">${esc(b.priority_rationale)}</p><div class="note mt">${esc(b.chain_position)}</div></section><section class="subsection"><div class="row between"><h3>仍有待补证项</h3><button class="linkbtn small" data-branch-gaps="${esc(b.id)}">在补证队列中查看 →</button></div>${b.gaps.filter(id=>gaps().some(g=>g.id===id)).map(id=>`<div class="kv"><span class="mono">${esc(id.split('-').pop())}</span><span>${esc(byId('gaps',id)?.description)}</span></div>`).join('')}</section>`;
if(tab==='claims')return `<div class="note" style="margin-bottom:20px">先看主张的限定表达，再打开来源核对原文；来源数量不代表证据已足够。</div>${b.claim_ids.map(id=>byId('claims',id)).filter(Boolean).map(c=>`<section class="claim"><span class="mono muted">${esc(c.id)}</span><h3>${esc(c.text)}</h3><div class="small muted">允许表达：${esc(arr(c.allowed_expression).join('；')||'待核验')}</div>${refs('sources',c.source_refs.map(r=>r.source_id),'来源 ')}<button class="linkbtn small mt" data-detail="claims" data-id="${esc(c.id)}">查看主张边界与反向线索 →</button></section>`).join('')}<section class="subsection mt"><h3>支持与反向线索</h3>${b.support?`<div class="section-label">支持依据</div>${textValue(b.support)}`:''}<div class="section-label mt">反向线索／限制</div>${textValue(b.counterevidence||b.counter_source_ids||'本支尚无完成核验的反向来源记录')}${refs('sources',b.source_ids,'关联来源 ')}</section>`;
if(tab==='bounds')return `<dl class="details-list"><div><dt>人群与场景</dt><dd>${textValue(b.population)}${b.context?`<p class="muted small mt">${esc(b.context)}</p>`:''}</dd></div><div><dt>上游因素</dt><dd>${textValue(b.upstream)}</dd></div><div><dt>下游推断边界</dt><dd>${textValue(b.downstream)}</dd></div><div><dt>时间尺度</dt><dd>${textValue(b.time_scale)}</dd></div><div><dt>加重／缓解因素</dt><dd>${textValue(b.modifiers)}</dd></div><div><dt>排除项</dt><dd>${textValue(b.exclusions)}</dd></div>${b.forbidden_expression?`<div><dt>不能这样表达</dt><dd>${textValue(b.forbidden_expression)}</dd></div>`:''}${b.solution_path?`<div><dt>护理路径与产品角色</dt><dd>${textValue(b.solution_path)}<p class="small muted mt">${esc(b.product_role)}</p></dd></div>`:''}</dl>`;
let draft=S().drafts[b.id];return `${draft?`<section class="judgment"><h3>意见待提交 · 尚未写入研究记录</h3><strong>${esc(L(draft.action))}</strong><p class="small mt">${esc(draft.reason)}</p></section>`:''}<div class="note">下列记录保留实际登记的决定者身份；代理意见不代表用户或临床专家确认。</div>${D().decisions.filter(x=>x.branch_id===b.id).map(x=>`<section class="claim mt"><div class="row between"><span class="mono muted">${esc(x.id)}</span>${tag(L(x.action))}</div><p class="prose mt">${esc(x.reason)}</p><p class="small muted mt">${esc(x.actor_label||'未记录')}（${esc(x.actor_type||'未记录身份')}）${x.invalidated?' · 已失效':''} · ${esc(x.decided_at||'未记录时间')}</p></section>`).join('')}`}
function directions(){
 const s=S(),d=D();let h=heading('方向与补证','科学证据和平台兴趣分别核验；有缺口的方向先保留为草案。',`<button data-action="drafts" ${C.latest(d,'review')?'':'disabled'}>生成 / 更新草案</button>`)+tabs('directionTab',[['candidates','候选方向',d.candidates.length],['gaps','待补证',gaps().length]],s.directionTab);
 if(s.directionTab==='gaps')return h+gapList();
 const c=byId('candidates',s.candidate)||d.candidates[0];if(!c)return h+'<div class="empty"><strong>尚无方向草案</strong><p>完成并冻结逐支审阅后，点击“生成 / 更新草案”。</p></div>';
 s.candidate=c.id;const g=C.gates(d,c,policy),eligible=currentCandidates().some(x=>x.id===c.id),current=eligible&&C.latest(d,'review');
 return h+`<div class="candidate-layout" role="tabpanel" id="panel-directionTab" aria-labelledby="tab-directionTab-candidates"><div class="branch-list" aria-label="选择方向草案">${d.candidates.map((x,i)=>`<button class="branch-item" data-candidate="${esc(x.id)}" aria-pressed="${x.id===c.id}"><span class="mono muted">方向 ${String(i+1).padStart(2,'0')}</span><h3>${esc(x.title)}</h3>${tag(currentCandidates().some(y=>y.id===x.id)?'本版方向草案':'原有 / 历史方向记录',x.id===c.id?'blue':'')}</button>`).join('')}</div><article class="detail"><div class="detail-head"><span class="mono muted">${esc(c.id)}</span><h2>${esc(c.title)}</h2></div><div class="detail-scroll"><div class="note">${current?'记录科学与兴趣评估后，再决定正式或试运行冻结。':'原有材料保留供阅读；请先冻结本版审阅，再生成本版草案。'}</div><div class="gate-grid">${[['science','科学证据'],['interest','平台兴趣']].map(([k,t])=>`<div class="gate"><span class="small muted">${t}</span><strong>${g[k].pass?'通过':'未通过'}</strong>${textValue(g[k].reasons)}</div>`).join('')}</div><section class="subsection"><h3>可以怎样表达</h3>${textValue(c.allowed_expression)}</section><section class="subsection"><h3>不能怎样表达</h3>${textValue(c.forbidden_expression)}</section><section class="subsection"><h3>关联的研究分支</h3><div class="ref-row">${c.branch_ids.map(id=>`<button class="ref" data-open-branch="${esc(id)}">${esc(byId('branches',id)?.title||id)} →</button>`).join('')}</div></section><details class="mt"><summary>完整方向记录</summary>${textValue(c)}</details></div><footer class="detail-foot"><button class="linkbtn small" data-candidate-gaps="${esc(c.id)}">查看缺口</button><div class="btn-row"><button data-action="assessment" ${current?'':'disabled'}>记录评估</button><button class="primary" data-action="freeze-direction" ${current?'':'disabled'}>选择并冻结方向</button></div></footer></article></div>`;
}
function gapFiltered(){const s=S();return gaps().filter(g=>JSON.stringify(g).toLowerCase().includes(s.gapQuery.toLowerCase())).filter(g=>s.gapFilter==='all'||s.gapFilter==='science'&&!/interest|platform/.test(g.category)||s.gapFilter==='interest'&&/interest|platform/.test(g.category)||s.gapFilter.startsWith('ids:')&&s.gapFilter.slice(4).split(',').includes(g.id))}
function gapList(){const s=S(),all=gapFiltered();s.gapPage=Math.min(s.gapPage,Math.max(1,Math.ceil(all.length/5)));return `<div class="page-body" role="tabpanel" id="panel-directionTab" aria-labelledby="tab-directionTab-gaps"><div class="toolbar"><div class="searchbox">${icon('search')}<input id="gap-search" type="search" data-input="gapQuery" aria-label="搜索待补证项" value="${esc(s.gapQuery)}" placeholder="搜索缺口或编号"></div><select id="gap-filter" aria-label="筛选补证类别"><option value="all" ${s.gapFilter==='all'?'selected':''}>全部类别</option><option value="science" ${s.gapFilter==='science'?'selected':''}>科学与流程缺口</option><option value="interest" ${s.gapFilter==='interest'?'selected':''}>平台兴趣缺口</option>${s.gapFilter.startsWith('ids:')?`<option value="${esc(s.gapFilter)}" selected>当前关联项</option>`:''}</select><span class="small muted" style="margin-left:auto">最多选 2 项</span></div><div class="table-wrap"><div class="list-header"><span>未关闭项 · 点击查看完整要求</span><span>缺口级别</span></div>${all.length?all.slice((s.gapPage-1)*5,s.gapPage*5).map(g=>`<article class="data-row"><input type="checkbox" aria-label="选择 ${esc(g.id)}" data-gap="${esc(g.id)}" ${s.selected.has(g.id)?'checked':''}><div class="grow"><div class="meta"><span class="mono muted">${esc(g.id)}</span><span class="small muted">${/interest|platform/.test(g.category)?'平台兴趣':'科学与流程'}</span></div><h3><button class="linkbtn clamp" data-detail="gaps" data-id="${esc(g.id)}">${esc(g.description)}</button></h3></div><div class="trailing">${tag(g.critical?'关键缺口':'待处理',g.critical?'warn':'')}</div></article>`).join(''):'<div class="empty"><strong>当前筛选没有结果</strong><button class="mt" data-action="clear-gaps">清除筛选</button></div>'}</div>${pager(all.length,s.gapPage,'gapPage')}<div class="detail-foot surface mt"><span class="small muted" id="selection-count">已选 ${s.selected.size} / 2 项 · 查看要求后按预算导出</span><div class="btn-row"><button class="linkbtn small" data-action="clear-selection" ${s.selected.size?'':'disabled'}>清空选择</button><button class="primary" data-action="request-preview" ${s.selected.size?'':'disabled'}>补证要求与请求 ${icon('arrow')}</button></div></div></div>`}
function delivery(){
 const d=D(),s=S(),dir=C.latest(d,'direction'),pack=C.latest(d,'package');
 let h=heading('研究交付','核对研究包与边界，导出当前资料或查阅冻结历史。')+tabs('deliveryTab',[['summary','当前研究包'],['history','版本历史',d.snapshots.length]],s.deliveryTab);
 if(s.deliveryTab==='history'){const all=[...d.snapshots].reverse();s.versionPage=Math.min(s.versionPage,Math.max(1,Math.ceil(all.length/5)));const p=s.versionPage;return h+`<div class="page-body" role="tabpanel" id="panel-deliveryTab" aria-labelledby="tab-deliveryTab-history"><div class="note" style="margin:18px 0">主控历史审计保留原时间与载荷；本页新决定单独记录，不冒用历史确认。</div><div class="table-wrap"><table class="history"><thead><tr><th>冻结版本</th><th>类型</th><th>状态</th><th class="hide-mobile">原始时间</th><th></th></tr></thead><tbody>${all.slice((p-1)*5,p*5).map(x=>`<tr><td><span class="mono">${esc(x.id)}</span>${x.audit_origin==='external_history'?'<div class="small muted">主控历史审计</div>':''}</td><td>${L(x.kind)}</td><td>${tag(L(x.status))}</td><td class="hide-mobile mono">${esc(x.created_at)}</td><td><button class="linkbtn" data-detail="snapshots" data-id="${esc(x.id)}">详情</button></td></tr>`).join('')}</tbody></table></div>${pager(all.length,p,'versionPage')}</div>`}
 const selection=dir?.content.selection,c=byId('candidates',selection?.candidate_id),p=d.package;
 const content=c?`<h2>${esc(c.title)}</h2><p class="prose mt">选择理由：${esc(selection.reason)}</p><div class="note mt">${selection.classification==='formal'?'正式候选方向':'含关键缺口的试运行方向'} · ${pack?'研究包已冻结':'研究包待冻结'}</div><section class="subsection"><h3>关联分支</h3>${c.branch_ids.map(id=>`<p><button class="linkbtn" data-open-branch="${esc(id)}">${esc(byId('branches',id)?.title||id)} →</button></p>`).join('')}</section><section class="subsection"><h3>主张与依据</h3>${refs('claims',c.claim_ids,'主张 ')}</section><section class="subsection"><h3>表达边界</h3>${textValue({允许表达:c.allowed_expression,禁止表达:c.forbidden_expression})}</section>`:p?`<div class="row between"><h2>原始研究摘要</h2>${tag('含缺口 · 试运行','warn')}</div><p class="prose mt">${esc(p.synthesis)}</p><hr class="rule"><h3>建议的解释顺序</h3><div class="steps-chain">${arr(p.knowledge_chain).map((x,i)=>`<div class="chain-item"><b>0${i+1}</b><div><h3>${esc(x.label||x.title)}</h3><p>${esc(x.content||x.solution_path)}</p><button class="linkbtn small" data-open-branch="${esc(x.branch_id)}">回看研究分支 →</button></div></div>`).join('')}</div><p class="small muted mt">${esc(p.chain_note)}</p><section class="subsection"><h3>表达边界</h3>${textValue(p.expression_boundaries)}</section>`:'<h2>尚无研究包</h2><p class="muted mt">完成取证、审阅与方向确认后，在这里冻结研究包。</p>';
 return h+`<div class="page-scroll" role="tabpanel" id="panel-deliveryTab" aria-labelledby="tab-deliveryTab-summary"><div class="delivery-layout"><section class="surface pad">${content}</section><aside class="stack"><section class="surface pad"><h3>交付状态</h3><p class="small muted mt">${dir?'当前方向按已记录的门槛与类型保留。':'已有研究包供内部理解与继续审阅；当前输入仍需重新确认。'}</p><div class="kv"><span>未关闭项</span><span>${gaps().length} 项</span></div><div class="kv"><span>当前冻结</span><span>${pack?'研究包已冻结':dir?'方向已冻结':'尚未冻结'}</span></div><button class="primary mt" data-action="freeze-package" ${dir?'':'disabled'}>冻结本版研究包</button><button class="linkbtn mt" data-go="directions" data-open-tab="gaps">返回补证 →</button></section><section class="surface pad"><h3>保留当前成果</h3><p class="small muted mt">导出已提交的材料与决定。尚未提交的审阅意见不会写入研究文件。获取附件随 HTML 保留，也可单独导出。</p><div class="btn-row mt"><button data-action="export-html">导出 HTML ↓</button><button data-action="export-json">导出 JSON ↓</button></div><button class="linkbtn mt" data-action="files">保存到本机 / 导入记录 →</button><p class="mono muted mt">${esc(d.revision)}</p></section></aside></div></div>`;
}

let dialogReturn=null,dialogTrail=[];
function showDialog(title,body,footer='',nested=false){$('#dialog').classList.remove('help-dialog');if(!nested){dialogTrail=[];dialogReturn=document.activeElement}else dialogTrail.push($('#dialog').innerHTML);$('#dialog').innerHTML=`<div class="modal-head"><div class="grow">${nested?'<button class="linkbtn small" data-action="dialog-back" style="margin-bottom:10px">← 返回上一条详情</button>':''}<h2 id="dialog-title">${esc(title)}</h2></div><button class="icon-btn" data-action="dialog-close" aria-label="关闭详情">${icon('close')}</button></div><div class="modal-body">${body}</div>${footer?`<div class="modal-footer">${footer}</div>`:''}`;if(!$('#dialog').open)$('#dialog').showModal();$('#dialog').scrollTop=0;$('#dialog').querySelector('input,select,textarea,button')?.focus()}
function closeDialog(){$('#dialog').close();dialogTrail=[];if(dialogReturn?.isConnected)dialogReturn.focus();else $('#content').focus({preventScroll:true})}
function pageHelp(){
  const help=pageHelpContent[S().view],title=sections.find(([id])=>id===S().view)[1];
  showDialog(`${title} · 使用帮助`,`<div class="usage-help"><section><h3>这一步做什么</h3><p>${esc(help.purpose)}</p></section><section><h3>你要做什么</h3><p>${esc(help.action)}</p></section><section><h3>在整个流程里</h3><p>${esc(help.role)}</p></section><section class="help-example"><h3>举个例子</h3><p>${esc(help.example)}</p></section>${help.note?`<p class="help-note">${esc(help.note)}</p>`:''}</div>`,`<button data-action="dialog-close">返回当前页面</button>`);
  $('#dialog').classList.add('help-dialog');
  $('#dialog [data-action="dialog-close"]').setAttribute('aria-label','关闭使用帮助');
}
function detail(key,id){if(key==='acquisitions'){acquisitionDetail(id);return;}const nested=$('#dialog').open;let x=key==='knowledge'?arr(D().knowledge_base)[0]:byId(key,id);if(!x)return;let title=x.title||x.text||x.indexed_title||x.id||'知识库对照';let body='';if(key==='sources'){body=`<div class="row wrap">${tag(L(x.read_level),'blue')}<span class="mono muted">${esc(x.id)}</span></div><dl class="details-list"><div><dt>研究摘要</dt><dd>${textValue(x.excerpt_or_summary)}</dd></div><div><dt>原始来源</dt><dd>${/^https?:\/\//.test(x.url||'')?`<a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">打开来源原页 ↗</a>`:'未记录可访问地址'}<p class="small muted mt">作者：${esc(arr(x.authors).join('；')||'未记录')}<br>发布日期：${esc(x.published_at||'未记录')} · 读取日期：${esc(x.accessed_at||'未记录')}</p></dd></div><div><dt>证据定位</dt><dd>${textValue(x.locator)}</dd></div><div><dt>研究局限</dt><dd>${textValue(x.limitations)}</dd></div><div><dt>质量核验</dt><dd>${textValue(x.quality)}</dd></div></dl>`}
else if(key==='claims'){body=`<span class="mono muted">${esc(x.id)}</span><dl class="details-list"><div><dt>主张</dt><dd>${esc(x.text)}</dd></div><div><dt>允许表达</dt><dd>${textValue(x.allowed_expression)}</dd></div><div><dt>禁止表达</dt><dd>${textValue(x.forbidden_expression)}</dd></div><div><dt>人群与场景</dt><dd>${textValue(x.population)}<p class="mt">${esc(x.context)}</p></dd></div><div><dt>时间范围</dt><dd>${textValue(x.time_scale)}</dd></div><div><dt>来源及其作用</dt><dd>${arr(x.source_refs).map(r=>`<div style="padding:8px 0"><span class="small muted">${esc(L(r.role))} · ${esc(r.locator||'定位见来源详情')}</span>${refs('sources',[r.source_id],'来源 ')}</div>`).join('')}</dd></div></dl>`}
else if(key==='gaps'){title='待补证项';body=`<div class="row wrap"><span class="mono muted">${esc(x.id)}</span>${tag(x.critical?'关键缺口':'待处理','warn')}</div><h3 class="mt">${esc(x.description)}</h3><dl class="details-list"><div><dt>当前状态</dt><dd>未关闭</dd></div><div><dt>关联范围</dt><dd>${esc(x.scope_id)}</dd></div><div><dt>已有进展／关闭说明</dt><dd>${textValue(x.closure_note)}</dd></div></dl><div class="note mt">需要取得真实材料并重新审阅；生成交接要求不算补证完成。</div>`}
else if(key==='signals'){const latest=signalAcquisition(x);title=x.indexed_title||`${x.platform} 平台线索`;const historical=`<dl class="details-list"><div><dt>原记录未核验原因</dt><dd>${textValue(x.missing_reason)}</dd></div><div><dt>日期与账号</dt><dd>发布时间：${esc(x.published_at||'未知')}<br>账号：${esc(x.account||'未知')}</dd></div><div><dt>互动指标</dt><dd>${textValue(x.metrics?Object.fromEntries(Object.entries(x.metrics).map(([k,v])=>[({views:'播放量',likes:'点赞数',comments:'评论数'})[k]||k,v])):'未知')}</dd></div><div><dt>受众地区</dt><dd>${textValue(x.audience_region)}</dd></div></dl>`;body=`<div class="row wrap">${tag(x.platform)}${tag('兴趣待核验','warn')}</div>${latest?`<div class="note mt"><strong>已补取视频资料与自动字幕</strong><p>${esc(latest.result_summary)}</p><p class="small muted">获取时间：${esc(observedLabel(latest.observed_at))}。新成果单独保存，原研究记录保留。</p></div>${videoFacts(latest)}<button class="primary mt" data-detail="acquisitions" data-id="${esc(latest.id)}">查看内容分析与字幕 →</button><details><summary>查看原研究记录 · ${esc(x.observed_at||'日期未记录')}</summary>${historical}</details>`:`<div class="note warn mt">目前仅为索引或受限访问线索，不能用来判定内容热度。</div>${historical}`}<p class="small muted mt">缺少受众地区与可比依据，单条视频不能证明主题热度。</p><p class="mt">${/^https?:\/\//.test(x.url||'')?`<a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">查看平台原页 ↗</a>`:'未记录线索链接'}</p>`}
else if(key==='snapshots'){title='冻结记录详情';body=`<span class="mono">${esc(x.id)}</span><dl class="details-list">${[['类型',L(x.kind)],['状态',L(x.status)],['输入版本',x.input_revision],['记录时间',x.created_at],['记录者',x.actor_label||'主控代理'],['状态说明',x.invalidation_reason||'当前记录中无失效说明'],['关联决定',x.decision_ids]].map(([t,v])=>`<div><dt>${t}</dt><dd>${textValue(v)}</dd></div>`).join('')}</dl><div class="note mt">完整审计载荷保留在下方原始记录及导出文件中。</div>`}
else if(key==='knowledge'){title='知识库对照记录';body=textValue(x)}
if(key==='sources')body=provenanceDetails(x)+body;body+=`<details><summary>完整原始记录</summary><pre>${esc(JSON.stringify(x,null,2))}</pre></details>`;showDialog(title,body,'',nested)}
function reviewForm(){const b=byId('branches',S().branch);if(!b)return;const draft=S().drafts[b.id]||C.review(D(),b.id)||{};showDialog('记录审阅意见',`<p class="small muted">${esc(b.title)}</p><div class="note mt">逐支写完后，点“提交全部审阅”登记决定者身份。这里保留的意见尚未提交。</div><form id="review-form" class="stack mt"><div class="field"><label for="review-decision">处理意见</label><select id="review-decision">${[['gap','保留，继续补证'],['keep','保留，可用于后续判断'],['revise','修正后再判断'],['exclude','本轮排除']].map(([v,t])=>`<option value="${v}" ${draft.action===v?'selected':''}>${t}</option>`).join('')}</select></div><div class="field"><label for="review-reason">判断理由 · 必填</label><textarea id="review-reason" required>${esc(draft.reason||'')}</textarea></div><div class="field"><label for="review-changes">需要补齐或修改什么？</label><textarea id="review-changes">${esc(draft.required_changes||'')}</textarea></div><p class="error" id="review-error" role="alert"></p></form>`,`<button data-action="dialog-close">取消</button><button data-action="save-review">保留待提交意见</button><button class="primary" data-action="save-review-next">保留并看下一支 ${icon('arrow')}</button>`)}
function saveReview(next){const reason=$('#review-reason').value.trim();if(!reason){$('#review-error').textContent='请填写判断理由。';$('#review-reason').focus();return}const s=S(),b=byId('branches',s.branch);s.drafts[b.id]={action:$('#review-decision').value,reason,required_changes:$('#review-changes').value.trim()||null};const i=D().branches.indexOf(b);if(next&&i<D().branches.length-1){s.branch=D().branches[i+1].id;s.branchTab='overview'}else s.branchTab='records';closeDialog();render();toast('意见已保留待提交；逐支完成后点“提交全部审阅”。')}
function requestPreview(){const ids=[...S().selected];if(!ids.length||ids.length>2)return;showDialog('补证要求与请求',`<div class="note">导出前按原任务累计预算检查。每份请求对应一个目标，不会自动执行研究、预占额度或关闭缺口；执行方仍需核对最新记录。</div><ol class="step-list mt">${ids.map(id=>`<li><div><span class="mono muted">${esc(id)}</span><p>${esc(byId('gaps',id).description)}</p></div></li>`).join('')}</ol><form data-operation="request" class="stack mt"><div class="field"><label for="request-stage">本次阶段</label><select id="request-stage" name="stage"><option value="S2">S2 · 指定缺口补证</option><option value="S1">S1 · 原有范围取证</option></select></div><div class="field"><label for="request-gap">本份请求关联缺口</label><select id="request-gap" name="gap_id">${ids.map(id=>`<option>${esc(id)}</option>`).join('')}</select></div><div class="field"><label for="request-target">稳定目标 ID（S2 必填，已有目标沿用原 ID）</label><input id="request-target" name="target" placeholder="先查看策略与预算记录中的已有目标"></div><div class="field"><label for="request-category">来源类别（S1 使用）</label><select id="request-category" name="category">${Object.entries(policy.accounting.s1_categories).map(([id,value])=>`<option value="${esc(id)}">${esc(id)} · ${esc(typeof value==='string'?value:JSON.stringify(value))}</option>`).join('')}</select></div><div class="field"><label for="request-route">实际执行路线 · 必填</label><input id="request-route" name="route" required placeholder="沿用研究记录里的路线名称"></div><p data-operation-error class="error" role="alert"></p><button type="submit" class="primary">检查预算并导出请求</button></form>`)}
function newTask(){showDialog('新建研究任务',`<div class="note">先确定问题和边界。创建后可导出任务交给 Codex 取证；网页不会自动联网研究。</div><form id="new-task-form" class="stack mt"><div class="field"><label for="new-id">任务 ID · 唯一编号</label><input id="new-id" required placeholder="例如 SK-NEW-001"></div><div class="field"><label for="new-topic">想研究什么？</label><input id="new-topic" required placeholder="例如：频繁清洁与皮肤紧绷的关系"></div><div class="field"><label for="new-mode">从哪里开始研究？</label><select id="new-mode"><option value="behavior">从行为出发 · 行为型</option><option value="result">从表象或结果出发 · 结果型</option></select></div><div class="field"><label for="new-objective">本次研究目标</label><textarea id="new-objective" required></textarea></div><div class="field"><label for="new-questions">核心问题 · 每行一项</label><textarea id="new-questions" required></textarea></div><div class="field"><label for="new-exclude">明确不做什么？· 每行一项</label><textarea id="new-exclude" required>不做个体诊断、处方及具体品牌推荐</textarea></div><div class="field"><label for="new-product">产品在这次研究里的作用</label><input id="new-product" required value="仅作机制理解，不作具体产品推荐"></div><p id="new-error" data-operation-error class="error" role="alert"></p><button type="submit" class="primary">校验范围并创建任务</button></form>`)}
function newPreview(){run(async()=>{const form=$('#new-task-form');if(!form.reportValidity())return;const task={id:$('#new-id').value.trim(),topic:$('#new-topic').value.trim(),mode:$('#new-mode').value,objective:$('#new-objective').value.trim(),core_questions:lines($('#new-questions').value),exclude:lines($('#new-exclude').value),product_role:$('#new-product').value.trim()};if(DATA.some(d=>d.run_id===task.id))throw Error('该任务 ID 已存在，请使用新的编号。');await load(C.create(policy,task,boot.config_path));S().dirty=true;render();toast('任务已创建，尚未研究。请保存或导出任务。')})}
let toastTimer;function toast(msg){clearTimeout(toastTimer);$('#toast').textContent=msg;toastTimer=setTimeout(()=>$('#toast').textContent='',5000)}
function closeMenu(){$('#app').classList.remove('menu-open');document.querySelector('[data-action="menu"]').setAttribute('aria-expanded','false');if(window.innerWidth<=800)$('#sidebar').setAttribute('inert','')}
function syncMenu(){if(window.innerWidth>800){$('#sidebar').removeAttribute('inert');$('#app').classList.remove('menu-open')}else if(!$('#app').classList.contains('menu-open'))$('#sidebar').setAttribute('inert','')}
document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b||!initialized)return;if(b.dataset.go){navigate(b.dataset.go,b.dataset.openTab);return}if(b.dataset.tab){const s=S();s[b.dataset.tab]=b.dataset.value;if(b.dataset.tab==='evidenceTab'){s.page=1;s.query=''}render();$(`#tab-${b.dataset.tab}-${b.dataset.value}`)?.focus({preventScroll:true});return}if(b.dataset.branch){S().branch=b.dataset.branch;render();document.querySelector(`[data-branch="${b.dataset.branch}"]`)?.focus({preventScroll:true});return}if(b.dataset.openBranch){S().branch=b.dataset.openBranch;S().branchTab='overview';if($('#dialog').open)closeDialog();navigate('review');return}if(b.dataset.candidate){S().candidate=b.dataset.candidate;render();document.querySelector(`[data-candidate="${b.dataset.candidate}"]`)?.focus({preventScroll:true});return}if(b.dataset.detail){detail(b.dataset.detail,b.dataset.id);return}if(b.dataset.page){S()[b.dataset.page]+=Number(b.dataset.delta);render();document.querySelector('.table-wrap')?.scrollTo(0,0);return}if(b.dataset.branchGaps||b.dataset.candidateGaps){const x=b.dataset.branchGaps?byId('branches',b.dataset.branchGaps):byId('candidates',b.dataset.candidateGaps);const ids=x.gaps||[...arr(x.science_gate?.gap_ids),...arr(x.interest_gate?.gap_ids)];S().gapFilter='ids:'+ids.join(',');S().gapQuery='';S().gapPage=1;navigate('directions','gaps');return}const a=b.dataset.action;if(a==='menu'){$('#app').classList.add('menu-open');$('#sidebar').removeAttribute('inert');b.setAttribute('aria-expanded','true');$('#nav button').focus()}else if(a==='menu-close'){closeMenu();document.querySelector('[data-action="menu"]').focus()}else if(a==='page-help')pageHelp();else if(a==='dialog-close')closeDialog();else if(a==='dialog-back'){const old=dialogTrail.pop();if(old){$('#dialog').innerHTML=old;$('#dialog').scrollTop=0;$('#dialog button')?.focus()}}else if(a==='review-form')reviewForm();else if(a==='save-review'||a==='save-review-next')saveReview(a.endsWith('next'));else if(a==='request-preview')requestPreview();else if(a==='new-task')newTask();else if(a==='new-preview')newPreview();else if(a==='clear-search'){S().query='';S().sourceFilter='all';S().page=1;render();$('#material-search').focus()}else if(a==='clear-gaps'){S().gapQuery='';S().gapFilter='all';S().gapPage=1;render()}else if(a==='clear-selection'){S().selected.clear();render()}else if(a)handleAction(a,b);});
document.addEventListener('change',e=>{if(e.target.id==='task-switch'){active=Number(e.target.value);render();toast('已切换研究任务；各任务的浏览位置和待提交意见分别保留。')}else if(e.target.id==='source-filter'){S().sourceFilter=e.target.value;S().page=1;render()}else if(e.target.id==='article-part'){articlePart(e.target.dataset.id,e.target.value)}else if(e.target.id==='video-part'){videoPart(e.target.dataset.id,e.target.value)}else if(e.target.id==='import-file'){run(async()=>{const file=e.target.files[0];if(file)await load(JSON.parse(await file.text()));})}else if(e.target.id==='gap-filter'){S().gapFilter=e.target.value;S().gapPage=1;render()}else if(e.target.dataset.gap){const set=S().selected,id=e.target.dataset.gap;if(e.target.checked&&set.size>=2){e.target.checked=false;toast('每次最多选择 2 项；先清除一项再添加。');return}if(e.target.checked)set.add(id);else set.delete(id);$('#selection-count').textContent=`已选 ${set.size} / 2 项 · 查看要求后按预算导出`;document.querySelector('[data-action="request-preview"]').disabled=!set.size;document.querySelector('[data-action="clear-selection"]').disabled=!set.size}});
document.addEventListener('input',e=>{if(!e.target.dataset.input)return;const key=e.target.dataset.input,id=e.target.id,pos=e.target.selectionStart;S()[key]=e.target.value;S()[key==='query'?'page':'gapPage']=1;render();const input=document.getElementById(id);input.focus({preventScroll:true});try{input.setSelectionRange(pos,pos)}catch{}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#dialog').open)closeMenu();const tab=e.target.closest('[role="tab"]');if(!tab||!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const list=[...tab.parentElement.querySelectorAll('[role="tab"]')],i=list.indexOf(tab);const next=e.key==='Home'?0:e.key==='End'?list.length-1:(i+(e.key==='ArrowRight'?1:-1)+list.length)%list.length;list[next].click()});
document.addEventListener('submit',e=>{e.preventDefault();if(e.target.id==='review-form')saveReview(false);if(e.target.id==='new-task-form')newPreview();if(e.target.dataset.operation)handleSubmit(e.target)});
$('#dialog').addEventListener('cancel',e=>{e.preventDefault();closeDialog()});window.addEventListener('resize',syncMenu);
const lines=value=>String(value||'').split('\n').map(x=>x.trim()).filter(Boolean);
function currentCandidates(){return D().candidates.filter(a=>a.input_revision===D().revision&&!a.invalidated)}
function acquisitions(){return (ACQ.items||[]).filter(a=>a.run_id===D().run_id&&(a.kind==='video'?D().signals.some(s=>s.id===a.signal_id):D().sources.some(s=>s.id===a.source_id)))}
function acquisitionBatch(a){return ACQ.batches.find(b=>b.batch_id===a.batch_id)||{}}
function acquisitionExport(){const items=acquisitions();return {...ACQ,run_id:D().run_id,items,batches:ACQ.batches.filter(b=>items.some(a=>a.batch_id===b.batch_id))}}
function signalAcquisition(s){return acquisitions().find(a=>a.kind==='video'&&a.signal_id===s.id)}
function acquisitionStatus(a){return a.kind==='video'?(a.video.content_analysis?'含中文概要与分析':'视频资料与自动字幕已取得'):a.status==='retrieved'?'正文已取得 · 待质量核验':'未取得开放全文'}
function acquisitionSummary(items){const papers=items.filter(a=>a.kind==='article'),videos=items.filter(a=>a.kind==='video');return [papers.length?`论文 ${papers.length} 篇（正文取得 ${papers.filter(a=>a.status==='retrieved').length} 篇）`:'',videos.length?`YouTube ${videos.length} 条（含自动字幕）`:''].filter(Boolean).join('；')||'当前任务暂无补取成果'}
function observedLabel(value){return value?new Date(value).toISOString().slice(0,19).replace('T',' ')+' UTC':'未记录'}
function videoFacts(a){const v=a.video,n=x=>x==null?'未取得':Number(x).toLocaleString('en-US');return `<dl class="details-list"><div><dt>发布账号</dt><dd>${esc(v.channel)}</dd></div><div><dt>发布时间 / 时长</dt><dd>${esc(v.published_on)} · ${Math.floor(v.duration_seconds/60)} 分 ${v.duration_seconds%60} 秒</dd></div><div><dt>互动数据快照</dt><dd>播放 ${n(v.metrics.views)} · 点赞 ${n(v.metrics.likes)} · 评论数 ${n(v.metrics.comments)}<p class="small muted">采集于 ${esc(observedLabel(a.observed_at))}；评论数不代表已取得评论正文。</p></dd></div></dl>`}
function videoDetail(a){
 const v=a.video,analysis=v.content_analysis;
 showDialog('YouTube 获取成果',`<div class="row wrap">${tag('YouTube','blue')}${analysis?tag('中文概要与分析','blue'):''}${tag('英文自动字幕')}</div><h3 class="mt">${esc(analysis?.title_zh||a.title)}</h3>${analysis?`<p class="small muted">${esc(a.title)}</p>`:''}<div class="field mt"><label for="video-part">选择查看内容</label><select id="video-part" data-id="${esc(a.id)}">${analysis?'<option value="summary">中文概要与核心观点</option><option value="analysis">内容分析与研究用途</option>':''}<option value="overview">视频资料与互动快照</option><option value="transcript">英文自动字幕 · 阅读版</option><option value="vtt">英文自动字幕 · 原始时间片</option></select></div><div id="video-content" class="mt"></div><details><summary>获取来源与使用限制</summary><p class="small">关联平台线索 ${esc(a.signal_id)} · 获取于 ${esc(observedLabel(a.observed_at))}<br>获取渠道 ${esc(a.channel)} · ${esc(acquisitionBatch(a).tool_version)}<br>批次 ${esc(a.batch_id)}<br>原始证据 ${esc(a.raw_evidence)}<br>字幕证据 ${esc(v.subtitles.raw_evidence)}</p>${a.limits.map(x=>`<p class="small mt">${esc(x)}</p>`).join('')}${analysis?`<p class="small mt">中文内容由 AI 于 ${esc(analysis.prepared_on)} 整理。依据：${esc(analysis.basis)}${esc(analysis.review_status)}</p>`:''}</details>`,'',$('#dialog').open);
 videoPart(a.id,analysis?'summary':'overview');
}
function videoPart(id,part){
 const a=acquisitions().find(x=>x.id===id),el=$('#video-content');if(!a?.video||!el)return;
 const v=a.video,sub=v.subtitles,analysis=v.content_analysis;
 if((part==='summary'||part==='analysis')&&analysis){
  const summary=part==='summary';
  el.innerHTML=`<p class="small muted">${summary?'原视频内容的中文概括':'以下为 AI 内容分析，区别于原视频观点'} · 基于自动字幕，尚未经人工校对</p><div class="video-reader video-summary mt" role="region" aria-label="${summary?'中文概要与核心观点':'内容分析与研究用途'}" tabindex="0">${summary?`<section class="subsection"><h3>整篇讲什么</h3><p>${esc(analysis.overview)}</p></section><section class="subsection"><h3>核心观点 · 原视频</h3><ul class="text-list">${analysis.key_points.map(x=>`<li><strong>${esc(x.title)}</strong> <a class="small" href="${esc(v.url+'&t='+x.start_seconds+'s')}" target="_blank" rel="noopener noreferrer" aria-label="在原视频核对：${esc(x.title)}（${esc(x.source_label)}）">${esc(x.source_label)} ↗</a><p>${esc(x.text)}</p></li>`).join('')}</ul><p class="small muted mt">${esc(analysis.care_boundary)}</p></section><section class="subsection"><h3>内容解读 · AI 分析</h3><p>${esc(analysis.interpretation)}</p></section>`:analysis.analysis_sections.map(x=>`<section class="subsection"><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p></section>`).join('')}</div>`;
 }else if(part==='overview'){
  el.innerHTML=`${videoFacts(a)}<div class="operation-bar"><a href="${esc(v.url)}" target="_blank" rel="noopener noreferrer">打开原视频 ↗</a><a href="${esc(v.channel_url)}" target="_blank" rel="noopener noreferrer">查看发布账号 ↗</a></div><p class="note mt">已取得 ${sub.cue_count} 条字幕时间片，整理为 ${sub.text_line_count} 行英文。自动字幕尚未经人工校对，兴趣门槛仍待核验。</p><details><summary>视频简介（原文）</summary><div class="reader video-reader mt" role="region" aria-label="视频简介原文" tabindex="0">${esc(v.description)}</div></details>`;
 }else{
  const raw=part==='vtt';el.innerHTML=`<p class="note">英文自动字幕，未经人工校对。${raw?'原始 VTT 保留时间戳及滚动字幕的重复文本。':esc(sub.processing)}</p><div class="reader video-reader mt" role="region" aria-label="${raw?'字幕原始时间片':'字幕阅读内容'}" tabindex="0">${esc(raw?sub.vtt:sub.text)}</div><div class="operation-bar"><button data-action="export-subtitle-text" data-id="${esc(id)}">下载字幕 TXT ↓</button><button data-action="export-subtitle-vtt" data-id="${esc(id)}">下载原始 VTT ↓</button></div>`;
 }
}

function sourceHost(s){try{return new URL(s.url).hostname.replace(/^www\./,'')}catch{return '未记录网址'}}
function sourceBadges(s){const host=sourceHost(s),a=acquisitions().find(a=>a.source_id===s.id);return `<div class="provenance">${tag(host==='pubmed.ncbi.nlm.nih.gov'?'PubMed 条目':host,'blue')}${a?tag(a.status==='retrieved'?'PubMed MCP 补取 · 已取得正文':'PubMed MCP 补取 · 本次未取得全文',a.status==='retrieved'?'blue':'warn'):''}</div>`}
function provenanceDetails(s){const logs=D().search_log.filter(l=>(l.source_ids||[]).includes(s.id)),found=logs.find(l=>/search/i.test(l.route||'')),a=acquisitions().find(a=>a.source_id===s.id);return `${sourceBadges(s)}<dl class="details-list"><div><dt>最早可追溯获取记录</dt><dd>${found?`网络检索 · ${esc(found.route)}<p class="small muted">${esc(found.id)} · ${esc(found.query||found.query_text||'')}</p>`:logs.length?`已有原页读取记录，未单独记录最初发现渠道。<p class="small muted">${esc(logs[0].id)} · ${esc(logs[0].route||'未标注路线')}</p>`:'原研究包未单独记录最初发现渠道。'}</dd></div><div><dt>本次补取</dt><dd>${a?`${esc(a.channel)} · ${esc(acquisitionBatch(a).acquired_on)}<p>${esc(a.result_summary)}</p><button class="linkbtn" data-detail="acquisitions" data-id="${esc(a.id)}">查看实际获取成果 →</button>`:'未参与这次 PubMed MCP 试跑。'}</dd></div></dl>`}
function acquisitionDetail(id){const a=acquisitions().find(x=>x.id===id);if(!a)return;if(a.kind==='video'){videoDetail(a);return;}const batch=acquisitionBatch(a),v=a.article;const links=v?[['PubMed 条目',v.pubmedUrl],['PMC 全文',v.pmcUrl]]:[];showDialog('实际获取成果',`<div class="row wrap">${tag(a.status==='retrieved'?'已取得正文':'本次未取得全文',a.status==='retrieved'?'blue':'warn')}${tag('已有文献补取')}</div><h3 class="mt">${esc(a.title)}</h3><p class="small muted mt">${esc(a.channel)} · ${esc(acquisitionBatch(a).acquired_on)}<br>关联资料 ${esc(a.source_id)} · DOI ${esc(a.doi)}${v?`<br>PMID ${esc(v.pmid)} · PMCID ${esc(v.pmcId)}`:''}</p><p class="mt">${esc(a.result_summary)}</p><div class="operation-bar">${links.filter(([,url])=>/^https?:\/\//.test(url||'')).map(([label,url])=>`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${label} ↗</a>`).join('')}</div><div class="note warn mt">${a.limits.map(x=>`<p>${esc(x)}</p>`).join('')}</div>${v?`<div class="field mt"><label for="article-part">阅读取得的原文内容</label><select id="article-part" data-id="${esc(a.id)}"><option value="abstract">摘要</option>${(v.sections||[]).map((s,i)=>`<option value="section:${i}">正文 ${i+1} · ${esc(s.title||'未命名章节')}</option>`).join('')}${(v.tables||[]).map((t,i)=>`<option value="table:${i}">数据表 ${i+1} · ${esc(t.label||t.caption||'')}</option>`).join('')}<option value="assets">图与附件指针（未读取附件）</option></select></div><div id="article-content" class="mt"></div>`:''}<details><summary>获取记录与技术来源</summary><p class="small">工具 ${esc(batch.tool)} · ${esc(batch.provider)}<br>批次 ${esc(batch.batch_id)}<br>证据位置 ${esc(a.raw_evidence)}<br>${esc(batch.note)}</p></details>`,'', $('#dialog').open);if(v)articlePart(id,'abstract')}
function articlePart(id,part){const a=acquisitions().find(x=>x.id===id)?.article,el=$('#article-content');if(!a||!el)return;const [kind,n]=part.split(':');const section=s=>`<h3>${esc(s.title||'')}</h3><div class="reader mt">${esc(s.text||'')}</div>${(s.subsections||[]).map(section).join('')}`;if(kind==='abstract')el.innerHTML=`<h3>摘要</h3><div class="reader mt">${esc(a.abstract||'本次未返回摘要')}</div>`;else if(kind==='section'&&a.sections[n])el.innerHTML=section(a.sections[n]);else if(kind==='table'&&a.tables[n]){const t=a.tables[n];el.innerHTML=`<h3>${esc(t.label||'数据表')}</h3><p class="mt">${esc(t.caption||'')}</p><div class="reader-table"><table>${t.rows.map((row,i)=>`<tr>${row.map(v=>`<${i<(t.headerRowCount||0)?'th':'td'}>${esc(v)}</${i<(t.headerRowCount||0)?'th':'td'}>`).join('')}</tr>`).join('')}</table></div><div class="reader mt">${esc(Array.isArray(t.footnotes)?t.footnotes.join('\n'):t.footnotes||'')}</div>`}else if(kind==='assets')el.innerHTML=`<p class="note">以下为接口返回的图与附件指针。未下载附件、未读取其内容；需要查看时请前往 PMC 原文。</p>${a.assets.map(x=>`<div class="list-item"><h3>${esc(x.label||x.id)}</h3><p>${esc(x.caption||'')}</p><p class="small muted">${esc(x.assetType)} · ${esc(x.href)}</p></div>`).join('')}`;}
async function run(fn){if(busy)return;busy=true;try{await fn()}catch(e){const el=$('[data-operation-error]');if(el)el.textContent=e.message;else showDialog('操作未完成',`<p class="error-banner" role="alert">${esc(e.message)}</p>`)}finally{busy=false}}
async function load(doc){const next=C.copy(doc),audit=await C.audit(next,policy);if(audit.errors.length)throw Error(audit.errors.join('\n'));let i=DATA.findIndex(d=>d.run_id===next.run_id);if(i<0){i=DATA.length;DATA.push(next);states.push(freshState(next))}else{DATA[i]=next;states[i]=freshState(next)}active=i;closeDialog();render();toast(audit.stale.length?'已载入；过期冻结已标为失效，需重新确认。':'研究记录已载入。')}
async function change(fn,message){const next=C.copy(D());await fn(next);const a=await C.audit(next,policy);if(a.errors.length)throw Error(a.errors.join('\n'));DATA[active]=next;S().dirty=true;closeDialog();render();toast(message+(a.stale.length?'；过期冻结已标为失效。':''))}
function actorFields(){return `<div class="field"><label for="actor-type">本次决定者身份</label><select id="actor-type" name="actor_type"><option value="user">使用者本人</option><option value="controller_delegate">主控代理</option><option value="qualified_reviewer">具备资质的审核者</option></select></div><div class="field"><label for="actor-label">姓名或可追溯标识 · 必填</label><input id="actor-label" name="actor_label" required></div><div class="field"><label for="actor-qualification">资质说明（如适用）</label><input id="actor-qualification" name="qualification"></div>`}
const actor=f=>({actor_type:f.get('actor_type'),actor_label:String(f.get('actor_label')||'').trim(),qualification:String(f.get('qualification')||'').trim()||null});
function operationForm(kind,body,button){return `<form data-operation="${kind}" class="stack mt">${body}<p data-operation-error class="error" role="alert"></p><button class="primary" type="submit">${button}</button></form>`}
function reviewRows(){return D().branches.map(b=>({branch_id:b.id,...(S().drafts[b.id]||C.review(D(),b.id)||{action:'gap',reason:'',required_changes:null})})).map(({branch_id,action,reason,required_changes})=>({branch_id,action,reason,required_changes:required_changes||null}))}
function reviewSubmit(){const rows=reviewRows();showDialog('提交全部分支审阅',`<p class="small muted">核对每支意见后登记本次身份。提交会使后续方向和交付冻结失效，需要重新确认。</p>${rows.map(r=>`<div class="list-item"><h3>${esc(byId('branches',r.branch_id).title)} · ${esc(L(r.action))}</h3><p>${esc(r.reason||'尚未填写意见，请返回该分支补齐。')}</p></div>`).join('')}${operationForm('reviews',actorFields(),'登记并提交全部意见')}`)}
function freezeForm(kind){const a=byId('candidates',S().candidate);if(kind==='direction'&&!currentCandidates().some(x=>x.id===a?.id))throw Error('请先生成并选择当前版本的方向草稿。');showDialog({review:'冻结本版分支审阅',direction:'确认并冻结方向',package:'冻结本版交付包'}[kind],`<div class="note">冻结保留输入、决定者、理由与证据链。后续修改可能使本版失效；冻结不代表证据缺口已关闭。</div>${operationForm('freeze-'+kind,`${kind==='direction'?`<p>${esc(a.title)}</p><input type="hidden" name="candidate_id" value="${esc(a.id)}"><div class="field"><label for="classification">交付分类</label><select id="classification" name="classification"><option value="trial_with_gaps">含缺口试运行</option><option value="formal">正式（需通过科学与兴趣门槛）</option></select></div><div class="field"><label for="selection-reason">选择理由 · 必填</label><textarea id="selection-reason" name="reason" required></textarea></div>`:''}${actorFields()}`,'检查并冻结')}`)}
function assessForm(){const a=byId('candidates',S().candidate);if(!currentCandidates().some(x=>x.id===a?.id))throw Error('历史方向仅供查阅，请先生成当前版本的方向草稿。');showDialog('记录方向评估',`<p>${esc(a.title)}</p><div class="note mt">填写评估不会替代证据核验，准入仍由完整材料与双门槛决定。</div>${operationForm('assess',`<input type="hidden" name="candidate_id" value="${esc(a.id)}"><div class="field"><label for="science-strength">科学证据强度</label><select id="science-strength" name="strength">${['unknown','weak','medium','strong'].map(v=>`<option value="${v}" ${a.science_gate.strength===v?'selected':''}>${({unknown:'未知',weak:'弱',medium:'中',strong:'强'})[v]}</option>`).join('')}</select></div><div class="field"><label for="science-reasons">科学判断理由 · 每行一项</label><textarea id="science-reasons" name="science_reasons" required>${esc(arr(a.science_gate.reasons).join('\n'))}</textarea></div><div class="field"><label for="interest-level">用户兴趣</label><select id="interest-level" name="level">${['unknown','low','medium','high'].map(v=>`<option value="${v}" ${a.interest_gate.level===v?'selected':''}>${({unknown:'未知',low:'低',medium:'中',high:'高'})[v]}</option>`).join('')}</select></div><div class="field"><label for="interest-reasons">兴趣判断理由 · 每行一项</label><textarea id="interest-reasons" name="interest_reasons" required>${esc(arr(a.interest_gate.reasons).join('\n'))}</textarea></div><div class="field"><label for="comparison-basis">用于比较的基准</label><textarea id="comparison-basis" name="comparison_basis">${esc(a.interest_gate.comparison_basis||'')}</textarea></div><fieldset><legend>关联平台材料</legend>${D().signals.map(s=>`<label class="inline-check"><input name="signal_ids" type="checkbox" value="${esc(s.id)}" ${a.signal_ids.includes(s.id)?'checked':''}><span>${esc(s.id)} · ${esc(s.indexed_title||s.platform)}</span></label>`).join('')||'<p class="small muted">还没有平台材料。</p>'}</fieldset>`,'保存评估')}`)}
function filesDialog(){let keys=[];try{for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k.startsWith('sk-workbench-v01:'))keys.push(k.slice('sk-workbench-v01:'.length))}}catch{}showDialog('保存 / 导入 / 导出',`<div class="note">页面里的修改不会自动写回磁盘文件。保存到本机浏览器可供恢复；长期留存请导出 JSON，发给别人阅读请导出 HTML。</div><h3 class="mt">当前任务 · ${esc(D().run_id)}</h3><div class="operation-bar"><button data-action="save-local">保存到本机浏览器</button><button data-action="export-json">导出研究 JSON</button><button data-action="export-html">导出完整 HTML</button><button data-action="export-acquisitions">导出获取成果 JSON</button></div><div class="field mt"><label for="import-file">导入研究 JSON（相同 ID 会替换当前浏览器里的该任务）</label><input id="import-file" type="file" accept=".json,application/json"></div>${keys.length?operationForm('restore',`<div class="field"><label for="saved-run">恢复本机已保存任务</label><select id="saved-run" name="run_id">${keys.sort().map(k=>`<option>${esc(k)}</option>`).join('')}</select></div>`,'恢复所选任务'):'<p class="small muted mt">本机浏览器尚无已保存任务。</p>'}`)}
function download(value,name,type='application/json'){const blob=new Blob([type==='application/json'?JSON.stringify(value,null,2):value],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportHTML(){const html=document.documentElement.cloneNode(true);html.querySelector('#dialog').removeAttribute('open');html.querySelector('#dialog').innerHTML='';html.querySelector('#content').innerHTML='';html.querySelector('#toast').textContent='';html.querySelector('#app').classList.remove('menu-open');html.querySelector('body').removeAttribute('data-ready');const data={...boot,runs:[C.copy(D())],acquisitions:acquisitionExport()};html.querySelector('#boot-data').textContent=JSON.stringify(data).replace(/</g,'\\u003c');download('<!doctype html>\n'+html.outerHTML,D().run_id+'-工作台.html','text/html')}
function handleAction(a,b){if(a==='files')filesDialog();else if(a==='policy')showDialog('策略与预算记录',`<p class="note">沿用原任务累计额度；页面接入和全文补取不会重置额度。未执行的请求不计作实际消耗。</p><h3 class="mt">当前预算记录</h3>${textValue(C.budget(D(),policy))}<details><summary>绑定策略原始记录</summary><pre>${esc(JSON.stringify(policy,null,2))}</pre></details><details><summary>检索与读取日志（${D().search_log.length} 条）</summary><pre>${esc(JSON.stringify(D().search_log,null,2))}</pre></details>`);else if(a==='submit-reviews')reviewSubmit();else if(a.startsWith('freeze-'))run(async()=>freezeForm(a.slice(7)));else if(a==='assessment')run(async()=>assessForm());else if(a==='drafts')run(async()=>{await change(d=>C.makeCandidates(d),'已生成当前审阅对应的方向草稿。');S().candidate=currentCandidates()[0]?.id;render()});else if(a==='save-local')run(async()=>{localStorage.setItem('sk-workbench-v01:'+D().run_id,JSON.stringify(D()));S().dirty=false;closeDialog();render();toast('已保存到本机浏览器。待提交意见请先提交；长期留存请导出。')});else if(a==='export-json')download(D(),D().run_id+'-研究记录.json');else if(a==='export-html')exportHTML();else if(a==='export-acquisitions')download(acquisitionExport(),D().run_id+'-实际获取成果.json');else if(a==='export-subtitle-text'||a==='export-subtitle-vtt'){const v=acquisitions().find(x=>x.id===b.dataset.id)?.video;if(v){const raw=a==='export-subtitle-vtt';download(raw?v.subtitles.vtt:v.subtitles.text,v.id+'.en.'+(raw?'vtt':'txt'),raw?'text/vtt':'text/plain')}}}
function handleSubmit(form){run(async()=>{if(!form.reportValidity())return;const f=new FormData(form),op=form.dataset.operation;if(op==='reviews'){await change(d=>C.saveReview(d,policy,reviewRows(),actor(f)),'全部分支审阅已提交。');S().drafts={};render()}else if(op.startsWith('freeze-')){const kind=op.slice(7),selection=kind==='direction'?{candidate_id:f.get('candidate_id'),classification:f.get('classification'),reason:String(f.get('reason')).trim()}:null;await change(d=>C.snapshot(d,policy,kind,actor(f),selection),'冻结成功；请保存或导出。')}else if(op==='assess'){await change(d=>{const a=d.candidates.find(x=>x.id===f.get('candidate_id'));C.invalidate(d,'direction','方向评估已修改，需重新确认');a.science_gate={...a.science_gate,strength:f.get('strength'),reasons:lines(f.get('science_reasons'))};a.interest_gate={...a.interest_gate,level:f.get('level'),reasons:lines(f.get('interest_reasons')),comparison_basis:String(f.get('comparison_basis')).trim()||null};a.signal_ids=f.getAll('signal_ids');const g=C.gates(d,a,policy);a.science_gate.status=g.science.pass?'pass':'insufficient';a.interest_gate.status=g.interest.pass?'pass':'insufficient'},'方向评估已保存。')}else if(op==='restore'){const raw=localStorage.getItem('sk-workbench-v01:'+f.get('run_id'));if(!raw)throw Error('本机没有这份已保存记录。');await load(JSON.parse(raw))}else if(op==='request'){const request=Object.fromEntries([...f].map(([k,v])=>[k,String(v).trim()]));if(!request.route)throw Error('请填写实际执行路线。');const result=C.canRequest(D(),policy,request);if(!result.allowed)throw Error(result.reasons.join('\n'));download({schema_version:'0.1',run_id:D().run_id,input_revision:D().revision,config_ref:D().config_ref,created_at:new Date().toISOString(),status:'not_executed',request,gap:byId('gaps',request.gap_id),budget:C.budget(D(),policy),note:'本请求未执行、未预占额度。执行前核对当前记录与累计预算；交回来源、定位、局限及未解决部分。'},D().run_id+'-补证请求.json');toast('预算检查通过，已导出未执行的请求。')}})}
window.addEventListener('beforeunload',e=>{if(states.some(s=>s.dirty||Object.keys(s.drafts).length)){e.preventDefault();e.returnValue=''}});

try {if(!await C.verifyPolicy(policy))throw Error('绑定策略校验失败');for(const d of DATA){const a=await C.audit(d,policy);if(a.errors.length)throw Error(d.run_id+'：'+a.errors.join('；'));}initialized=true;render();syncMenu();document.body.dataset.ready='true';}catch(e){$('#content').innerHTML='<div class="error-banner" role="alert">'+esc(e.message)+'</div>';}



})();
