import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import {chapterHTML,units} from './原版03内容.mjs';
const work=path.dirname(fileURLToPath(import.meta.url)), project=path.resolve(work,'../..');
const target=path.join(project,'03_交付物/认知连续性-图解手册.html');
const baseline=path.join(project,'01_输入/历史图解手册_2026-09-20/output/认知连续性手册/认知连续性-图解手册.html');
const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
const original=fs.readFileSync(baseline,'utf8');
assert.equal(sha(original),'5e25d103bcee628d2093c21ed19720b13c5f9a00fdb2572bc6333d7b9599c171');
const marker=i=>'<section role="tabpanel" id="panel-'+i+'"';
const panel=(html,i)=>html.slice(html.indexOf(marker(i)),html.indexOf(marker(i+1)));
const current=fs.readFileSync(target,'utf8');
assert.equal(panel(current,0),panel(original,0));
assert.equal(panel(current,1),panel(original,1));
let html=original.slice(0,original.indexOf(marker(2)))+chapterHTML()+original.slice(original.indexOf(marker(3)));
const replace=(a,b)=>{assert.ok(html.includes(a),'Missing replacement: '+a);html=html.replace(a,b);};
replace('已展开两章','已展开三章');
replace('已展开“视觉锚点”和“视觉持续性”，其余分类保留入口。','已展开“视觉锚点”“视觉持续性”和“视觉层级”，其余分类保留入口。');
replace('点击切换分类 · 已展开 01 视觉锚点 / 02 视觉持续性','点击切换分类 · 已展开 01 视觉锚点 / 02 视觉持续性 / 03 视觉层级');
replace('<em>本次新增</em>','<em>已展开</em>');
replace('<small>Visual Hierarchy</small></span><em>待制作</em>','<small>Visual Hierarchy</small></span><em>本次新增</em>');
html=html.replaceAll('前两章已完成。此处保留分类说明','前三章已展开。此处保留分类说明');
replace('视觉锚点＋视觉持续性 · 共 18 组图解','视觉锚点＋视觉持续性＋视觉层级 · 共 27 组图解');
replace('图片、文字和交互全部内嵌，保存这一个 HTML 即可离线阅读。','01、02 保留原内嵌图片；03 图片位于 assets。请将本 HTML 与 assets 文件夹一起保存，即可离线阅读。');
replace('</details></footer>','<br><a href="assets/visual-hierarchy/prompts.json" download="visual-hierarchy-prompts.json">下载视觉层级插图记录</a></details></footer>');
replace('selectTab(1);','selectTab(2);');
replace('</style>','#panel-2 .hierarchy-review{width:100%;border-collapse:collapse;font-size:15px;margin:20px 0}#panel-2 .hierarchy-review th,#panel-2 .hierarchy-review td{text-align:left;padding:12px;border-bottom:1px solid #d5d9da;vertical-align:top}#panel-2 .hierarchy-review th{white-space:nowrap;color:#003049}#panel-2 .chapter-end b{font-size:24px;line-height:1.5}@media(max-width:600px){#panel-2 .hierarchy-review{font-size:14px}#panel-2 .hierarchy-review th,#panel-2 .hierarchy-review td{padding:10px 6px}#panel-2 .chapter-end b{font-size:20px}}</style>');
assert.equal(panel(html,0),panel(original,0));
assert.equal(panel(html,1),panel(original,1));
assert.equal((panel(html,2).match(/class="lesson"/g)||[]).length,9);
const spec=JSON.parse(fs.readFileSync(path.join(work,'原版03视觉层级批次.json'),'utf8'));
const assets=path.join(project,'03_交付物/assets/visual-hierarchy');
fs.mkdirSync(assets,{recursive:true});
for(const unit of units){
 const item=spec.images.find(x=>x.id===unit.id);
 assert.ok(item.output && item.qa==='通过',unit.id+' 尚未通过图意检查');
 fs.copyFileSync(item.output,path.join(assets,unit.id+'.png'));
}
const record={version:spec.version,palette:spec.palette,referenceSha256:spec.reference.sha256,images:spec.images.map(({id,title,prompt,revision,qa})=>({id,title,prompt,revision,qa,file:id+'.png'}))};
fs.writeFileSync(path.join(assets,'prompts.json'),JSON.stringify(record,null,2)+'\n');
fs.writeFileSync(target,html);
console.log(JSON.stringify({html:target,sha256:sha(html),baselineUnchanged:sha(fs.readFileSync(baseline,'utf8'))===sha(original),panels01and02Unchanged:true,units:9,totalImages:(html.match(/<img /g)||[]).length-1,newAssets:units.length},null,2));
