const {chromium}=require('/Users/chengyu/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{pathToFileURL}=require('url');
const T=__dirname,P=path.resolve(T,'../../..'),D=path.join(P,'03_交付物/护肤科普研究首版');
const source=JSON.parse(fs.readFileSync(path.join(D,'acquisition-results.json'))),video=source.items.find(x=>x.kind==='video');
const result={started:new Date().toISOString(),version:'SK-WORKBENCH-20260926-r3',fallback:'Browser plugin unavailable; existing Playwright runtime used.',scope:'YouTube display, historical link, downloads, offline export, 390px layout; existing PubMed detail regression only.',checks:[],errors:[],requests:[]};
const check=name=>{result.checks.push(name);console.log('PASS '+name)};
(async()=>{
 const browser=await chromium.launch({headless:true});
 const context=await browser.newContext({viewport:{width:1365,height:900},acceptDownloads:true});
 context.on('page',p=>{p.setDefaultTimeout(8000);p.on('pageerror',e=>result.errors.push(e.message));p.on('console',m=>{if(m.type()==='error')result.errors.push(m.text())});p.on('request',r=>{if(/^https?:/.test(r.url()))result.requests.push(r.url())})});
 const page=await context.newPage();
 const nav=async p=>p.locator('#nav [data-go="evidence"]').click();
 const close=async p=>p.getByRole('dialog').getByRole('button',{name:'关闭详情',exact:true}).click();
 const acq=async p=>p.getByRole('tab',{name:/获取成果/}).click();
 const openVideo=async p=>p.getByRole('button',{name:video.title,exact:true}).click();
 const download=async(name,action)=>{const pending=page.waitForEvent('download');await action();const file=await pending;const target=path.join(T,'roundtrip-'+name);await file.saveAs(target);return {target,name:file.suggestedFilename()}};
 try{
  await page.goto(pathToFileURL(path.join(D,'index.html')).href);await page.locator('body[data-ready="true"]').waitFor();
  await nav(page);await acq(page);assert.equal(await page.locator('.data-row').count(),1);assert.doesNotMatch(await page.locator('.data-row').innerText(),/YouTube/);
  await page.getByRole('button',{name:'查看详情 ↗'}).click();assert.match(await page.getByRole('dialog').innerText(),/不能推断所有渠道/);await close(page);
  check('行为型任务仍仅展示对应的 PubMed 未取全文记录');
  await page.locator('#task-switch').selectOption('1');await page.locator('#nav [data-go="home"]').click();
  const shortcut=page.getByRole('button',{name:/查看获取成果/});assert.match(await shortcut.innerText(),/论文 1 篇.*YouTube 1 条/);await shortcut.click();assert.equal(await page.locator('.data-row').count(),2);
  check('结果型任务总览及获取成果正确汇总论文和 YouTube');
  const paper=source.items.find(x=>x.kind==='article'&&x.run_id==='SK-RES-001');
  await page.getByRole('button',{name:paper.title,exact:true}).click();assert.match(await page.getByRole('dialog').innerText(),/35340018/);assert.ok((await page.locator('#article-content').innerText()).length>100);await page.getByLabel('阅读取得的原文内容').selectOption('table:0');assert.ok(await page.locator('#article-content td').count()>3);await close(page);
  check('原 PubMed 摘要和表格阅读保持可用');
  await openVideo(page);const dialog=page.getByRole('dialog');
  assert.match(await dialog.innerText(),/American Academy of Dermatology/);assert.match(await dialog.innerText(),/2026-01-02/);assert.match(await dialog.innerText(),/播放 17,127 · 点赞 48 · 评论数 2/);assert.match(await dialog.innerText(),/2026-09-26 13:12:24 UTC/);
  assert.equal(await dialog.getByRole('link',{name:'打开原视频 ↗'}).getAttribute('href'),video.video.url);
  assert.equal(await dialog.getByRole('link',{name:'查看发布账号 ↗'}).getAttribute('href'),video.video.channel_url);
  await page.screenshot({path:path.join(T,'ui-desktop-video.png')});
  check('视频详情显示真实账号、发布日期、时长、指标快照与来源链接');
  await page.getByLabel('选择查看内容').selectOption('transcript');
  assert.equal(await page.getByRole('region',{name:'字幕阅读内容',exact:true}).textContent(),video.video.subtitles.text);
  const reader=await page.getByRole('region',{name:'字幕阅读内容',exact:true}).evaluate(e=>({height:e.clientHeight,scroll:e.scrollHeight,overflow:getComputedStyle(e).overflowY}));assert.ok(reader.height<=300&&reader.scroll>reader.height&&reader.overflow==='auto');
  const txt=await download('biIzSPOEQgQ.en.txt',()=>page.getByRole('button',{name:'下载字幕 TXT ↓'}).click());assert.equal(txt.name,'biIzSPOEQgQ.en.txt');assert.deepEqual(fs.readFileSync(txt.target),fs.readFileSync(path.join(T,'biIzSPOEQgQ.en.txt')));
  await page.getByLabel('选择查看内容').selectOption('vtt');assert.equal(await page.getByRole('region',{name:'字幕原始时间片'}).textContent(),video.video.subtitles.vtt);
  const vtt=await download('biIzSPOEQgQ.en.vtt',()=>page.getByRole('button',{name:'下载原始 VTT ↓'}).click());assert.equal(vtt.name,'biIzSPOEQgQ.en.vtt');assert.deepEqual(fs.readFileSync(vtt.target),fs.readFileSync(path.join(T,'biIzSPOEQgQ.en.vtt')));await close(page);
  check('字幕限定区域阅读，TXT 和原始 VTT 下载与试跑文件逐字节一致');
  await page.getByRole('tab',{name:/平台线索/}).click();
  const signal=page.locator('.data-row').filter({hasText:'RES-I01'});assert.match(await signal.innerText(),/已补取 · 兴趣待核验/);await signal.getByRole('button',{name:'查看详情 ↗'}).click();
  const history=dialog.locator('details').filter({has:page.locator('summary').filter({hasText:/查看原研究记录/})});await history.locator('summary').click();assert.match(await history.innerText(),/账号：未知/);
  await dialog.getByRole('button',{name:'查看视频与字幕 →'}).click();assert.equal(await dialog.getByRole('heading',{name:'YouTube 获取成果'}).count(),1);await dialog.getByRole('button',{name:'← 返回上一条详情'}).click();assert.equal(await dialog.getByRole('button',{name:'查看视频与字幕 →'}).count(),1);await close(page);
  check('原平台线索关联补取详情，历史未知字段保留且可返回');
  await page.locator('#sidebar [data-action="files"]').click();
  const json=await download('acquisitions.json',()=>dialog.getByRole('button',{name:'导出获取成果 JSON'}).click());const payload=JSON.parse(fs.readFileSync(json.target));assert.equal(json.name,'SK-RES-001-实际获取成果.json');assert.equal(payload.run_id,'SK-RES-001');assert.equal(payload.items.length,2);assert.equal(payload.batches.length,2);assert.deepEqual(payload.items.find(x=>x.kind==='video'),video);assert.ok(payload.items.every(x=>x.run_id==='SK-RES-001'));
  const html=await download('workbench.html',()=>dialog.getByRole('button',{name:'导出完整 HTML'}).click());
  await context.setOffline(true);const roundtrip=await context.newPage();await roundtrip.goto(pathToFileURL(html.target).href);await roundtrip.locator('body[data-ready="true"]').waitFor();assert.equal(await roundtrip.locator('#task-switch option').count(),1);await nav(roundtrip);await acq(roundtrip);assert.equal(await roundtrip.locator('.data-row').count(),2);await openVideo(roundtrip);await roundtrip.getByLabel('选择查看内容').selectOption('transcript');assert.equal(await roundtrip.getByRole('region',{name:'字幕阅读内容',exact:true}).textContent(),video.video.subtitles.text);await roundtrip.close();
  check('获取成果 JSON 仅导出当前任务；独立 HTML 离线重开保留视频与字幕');
  const mobile=await context.newPage();await mobile.setViewportSize({width:390,height:844});await mobile.goto(pathToFileURL(path.join(D,'index.html')).href);await mobile.locator('body[data-ready="true"]').waitFor();await mobile.addStyleTag({content:'*,*::before,*::after{transition:none!important;animation:none!important}'});
  await mobile.locator('#task-switch').selectOption('1');await mobile.getByRole('button',{name:'打开导航'}).click();await nav(mobile);await acq(mobile);await openVideo(mobile);await mobile.getByLabel('选择查看内容').selectOption('transcript');
  const bounds=await mobile.evaluate(()=>{const d=document.querySelector('#dialog'),r=d.getBoundingClientRect();return {vw:innerWidth,sw:document.documentElement.scrollWidth,left:r.left,right:r.right,dw:d.clientWidth,dsw:d.scrollWidth}});assert.ok(bounds.sw<=bounds.vw+1&&bounds.left>=0&&bounds.right<=bounds.vw&&bounds.dsw<=bounds.dw+1,JSON.stringify(bounds));await mobile.screenshot({path:path.join(T,'ui-mobile-subtitles.png')});
  check('390px 手机视频字幕详情无横向溢出');
  assert.deepEqual(result.errors,[]);assert.deepEqual(result.requests,[]);check('全程无脚本或控制台错误，无页面自动联网请求');result.status='passed';
 }catch(e){result.status='failed';result.failure=e.stack;await page.screenshot({path:path.join(T,'ui-failure.png')});process.exitCode=1;console.error(e)}finally{result.finished=new Date().toISOString();fs.writeFileSync(path.join(T,'ui-validation.json'),JSON.stringify(result,null,2)+'\n');await browser.close()}
})();
