function evidence(){
 const d=D(),s=S(),tab=s.evidenceTab,acq=acquisitions(),items=[['sources','科学来源',d.sources.length],['acquisitions','获取成果',acq.length],['claims','研究主张',d.claims.length],['signals','平台线索',d.signals.length],['knowledge','知识库对照',null]];
 let html=heading('证据材料','查原有证据，也能直接阅读工具实际获取的内容。')+tabs('evidenceTab',items,tab);
 if(tab==='knowledge'){const kb=d.knowledge_base||{};return html+`<div class="page-scroll surface pad" role="tabpanel" id="panel-evidenceTab" aria-labelledby="tab-evidenceTab-knowledge"><h2>本轮知识库对照</h2><div class="note mt">这里只展示本轮实际查询结果；未匹配不代表整个知识库没有相关知识。不会自动写入知识库。</div>${textValue(kb)}</div>`}
 const query=s.query.trim().toLowerCase(),input=tab==='acquisitions'?acq:d[tab];
 const all=input.filter(x=>JSON.stringify(x).toLowerCase().includes(query)).filter(x=>tab!=='sources'||s.sourceFilter==='all'||s.sourceFilter==='pubmed'&&sourceHost(x)==='pubmed.ncbi.nlm.nih.gov'||s.sourceFilter==='mcp'&&acq.some(a=>a.source_id===x.id));
 const total=all.length;s.page=Math.min(s.page,Math.max(1,Math.ceil(total/5)));
 html+=`<div class="page-body" role="tabpanel" id="panel-evidenceTab" aria-labelledby="tab-evidenceTab-${tab}"><div class="toolbar"><div class="searchbox">${icon('search')}<input id="material-search" data-input="query" type="search" aria-label="搜索当前材料" placeholder="搜索标题、关键词或资料编号" value="${esc(s.query)}"></div>${tab==='sources'?`<select id="source-filter" aria-label="筛选来源渠道"><option value="all" ${s.sourceFilter==='all'?'selected':''}>全部渠道</option><option value="pubmed" ${s.sourceFilter==='pubmed'?'selected':''}>PubMed 条目</option><option value="mcp" ${s.sourceFilter==='mcp'?'selected':''}>PubMed MCP 补取记录</option></select>`:`<span class="small muted">${tab==='signals'?'平台线索不等于兴趣已验证':tab==='acquisitions'?'按顶部所选研究任务展示':'每次打开一条详情'}</span>`}</div><div class="table-wrap">${tab==='acquisitions'?`<div class="note">PubMed 小样共尝试 2 篇已有文献：1 篇取得正文，1 篇未取得开放全文。新增来源 0，新增合格深读 0。本页只显示当前任务的 ${acq.length} 条。</div>`:''}<div class="list-header"><span>${items.find(x=>x[0]===tab)[1]}</span><span>状态 / 操作</span></div>${total?all.slice((s.page-1)*5,s.page*5).map(x=>materialRow(x,tab)).join(''):`<div class="empty"><strong>没有匹配的材料</strong><p>当前任务可能尚无此类记录，或需要调整搜索与筛选。</p><button class="mt" data-action="clear-search">清除搜索与筛选</button></div>`}</div>${pager(total,s.page,'page')}</div>`;
 return html;
}
function materialRow(x,key){
 const acquisition=key==='acquisitions',title=x.title||x.text||x.indexed_title||`${x.platform} 平台线索`,summary=acquisition?x.result_summary:x.excerpt_or_summary||x.allowed_expression||x.missing_reason||'',status=acquisition?x.status==='retrieved'?'正文已取得 · 待质量核验':'未取得开放全文':key==='sources'?L(x.read_level):key==='signals'?'兴趣待核验':'需限定表达';
 return `<article class="data-row"><div class="grow"><div class="meta"><span class="mono muted">${esc(x.id)}</span>${tag(status,acquisition||key==='signals'?'blue':'')}</div><h3><button class="linkbtn" data-detail="${key}" data-id="${esc(x.id)}">${esc(title)}</button></h3><p class="description clamp">${esc(arr(summary).join('；'))}</p>${key==='sources'?sourceBadges(x):acquisition?`<div class="provenance">${tag(x.channel)}${tag('已有资料补取')}${tag(ACQ.acquired_on)}</div>`:''}</div><div class="trailing"><button class="linkbtn small" data-detail="${key}" data-id="${esc(x.id)}">${acquisition&&x.status==='retrieved'?'阅读获取内容':'查看详情'} ↗</button></div></article>`;
}
