const {chromium}=require('/Users/chengyu/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{pathToFileURL}=require('url');
const P='/Users/chengyu/12_打工人程宇/02_项目/01_进行中/内容研究能力-护肤科普类',D=path.join(P,'03_交付物/护肤科普研究首版'),T=__dirname;
const evidence={started:new Date().toISOString(),fallback:'Browser plugin not available',checks:[],errors:[],files:{}};
(async()=>{const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1365,height:900},acceptDownloads:true});const page=await context.newPage();page.setDefaultTimeout(8000);page.on('pageerror',e=>evidence.errors.push(e.message));page.on('dialog',d=>d.accept());
const check=(name)=>{evidence.checks.push(name);console.log('PASS '+name)};
const nav=async(view)=>{await page.locator('#nav [data-go="'+view+'"]').click()};
const close=async()=>{await page.getByRole('dialog').getByRole('button',{name:/关闭详情|关闭使用帮助/}).click()};
const download=async(action,name)=>{const waiting=page.waitForEvent('download');await action();const file=await waiting;const target=path.join(T,name||file.suggestedFilename());await file.saveAs(target);return target};
try{
await page.goto(pathToFileURL(path.join(D,'index.html')).href);await page.locator('body[data-ready="true"]').waitFor();assert.equal(await page.locator('#task-switch option').count(),2);check('file:// 正式入口直接加载两份研究');
for(const v of ['home','scope','evidence','review','directions','delivery']){await nav(v);await page.getByRole('button',{name:'使用帮助',exact:true}).click();assert.match(await page.getByRole('dialog').innerText(),/这一步做什么[\s\S]*你要做什么[\s\S]*在整个流程里[\s\S]*举个例子/);await close()}
check('六个功能页与对应帮助可用');
await nav('evidence');assert.equal(await page.locator('.data-row').count(),5);await page.getByRole('button',{name:'下一页'}).click();assert.equal(await page.locator('.data-row').count(),2);check('原始七份来源按 5 条分页');
await page.getByLabel('筛选来源渠道').selectOption('mcp');assert.equal(await page.locator('.data-row').count(),1);assert.match(await page.locator('.data-row').innerText(),/SK-BEH-001-S004/);await page.getByRole('tab',{name:/获取成果/}).click();assert.equal(await page.locator('.data-row').count(),1);await page.getByRole('button',{name:'查看详情 ↗'}).click();assert.match(await page.getByRole('dialog').innerText(),/不能推断所有渠道/);await close();check('BEH 未取到全文保留来源和限制');
await page.locator('#task-switch').selectOption('1');await nav('evidence');await page.getByLabel('筛选来源渠道').selectOption('pubmed');assert.match(await page.locator('.data-row').innerText(),/RES-S05/);assert.doesNotMatch(await page.locator('.data-row').innerText(),/MCP 补取/);
await page.getByLabel('筛选来源渠道').selectOption('mcp');assert.match(await page.locator('.data-row').innerText(),/RES-S03/);check('PubMed 条目与 MCP 补取分开筛选');
await page.getByRole('tab',{name:/获取成果/}).click();await page.getByRole('button',{name:'阅读获取内容 ↗'}).click();assert.match(await page.getByRole('dialog').innerText(),/35340018/);assert.ok((await page.locator('#article-content').innerText()).length>100);await page.getByLabel('阅读取得的原文内容').selectOption('section:0');assert.ok((await page.locator('#article-content').innerText()).length>100);await page.getByLabel('阅读取得的原文内容').selectOption('table:0');assert.ok(await page.locator('#article-content td').count()>3);await page.screenshot({path:path.join(T,'desktop-acquisition.png')});await page.getByLabel('阅读取得的原文内容').selectOption('assets');assert.match(await page.locator('#article-content').innerText(),/未下载附件/);await close();check('取得的摘要、正文、真实表格、附件指针可直接阅读');
await page.getByRole('tab',{name:/科学来源/}).focus();await page.keyboard.press('ArrowRight');assert.equal(await page.getByRole('tab',{name:/获取成果/}).getAttribute('aria-selected'),'true');check('标签页键盘切换');
await nav('home');await page.screenshot({path:path.join(T,'desktop-home.png')});
// Bounded round-trip of real operations in disposable browser memory; source files remain unchanged.
await nav('review');const branches=await page.locator('[data-branch]').count();
for(let i=0;i<branches;i++){await page.locator('[data-branch]').nth(i).click();await page.getByRole('button',{name:/填写审阅意见/}).click();await page.getByLabel('判断理由 · 必填').fill('定向 UI 验证：保留真实研究缺口，仅验证审阅操作。');await page.getByLabel('需要补齐或修改什么？').fill('科学质量与平台兴趣仍待补齐。');await page.getByRole('button',{name:'保留待提交意见',exact:true}).click()}
await page.getByRole('button',{name:'提交全部审阅',exact:true}).click();await page.getByLabel('姓名或可追溯标识 · 必填').fill('UI 定向测试（非业务确认）');await page.getByRole('button',{name:'登记并提交全部意见'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
const freeze=async(button)=>{await page.getByRole('button',{name:button,exact:true}).click();await page.getByLabel('姓名或可追溯标识 · 必填').fill('UI 定向测试（非业务确认）');await page.getByRole('button',{name:'检查并冻结'}).click();await page.getByRole('dialog').waitFor({state:'hidden'})};
await freeze('冻结审阅');check('逐支意见提交并冻结审阅');
await nav('directions');await page.getByRole('button',{name:'生成 / 更新草案'}).click();await page.getByRole('button',{name:'记录评估'}).waitFor();await page.getByRole('button',{name:'记录评估'}).click();await page.getByLabel('科学判断理由 · 每行一项').fill('真实材料尚有关键缺口，不作合格结论。');await page.getByLabel('兴趣判断理由 · 每行一项').fill('平台指标尚未核验。');await page.getByRole('button',{name:'保存评估',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
await page.getByRole('button',{name:'选择并冻结方向'}).click();await page.getByLabel('交付分类').selectOption('formal');await page.getByLabel('选择理由 · 必填').fill('验证准入阻断');await page.getByLabel('姓名或可追溯标识 · 必填').fill('UI 定向测试（非业务确认）');await page.getByRole('button',{name:'检查并冻结'}).click();await page.getByRole('alert').filter({hasText:'正式双门槛未通过'}).waitFor();await page.getByLabel('交付分类').selectOption('trial_with_gaps');await page.getByRole('button',{name:'检查并冻结'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});check('方向生成及评估、正式阻断与含缺口试运行冻结');
await nav('delivery');await freeze('冻结本版研究包');const exported=await download(()=>page.getByRole('button',{name:'导出 JSON ↓',exact:true}).click(),'roundtrip-research.json');const doc=JSON.parse(fs.readFileSync(exported));assert.equal(doc.status,'frozen');assert.equal(doc.snapshots.at(-1).classification,'trial_with_gaps');const audit=await page.evaluate(async doc=>WorkbenchCore.audit(doc,JSON.parse(document.querySelector('#boot-data').textContent).policy),doc);assert.deepEqual(audit.errors,[]);assert.deepEqual(audit.stale,[]);check('研究包冻结及 JSON 导出审计通过');
await page.getByRole('button',{name:'保存到本机 / 导入记录 →'}).click();await page.getByRole('button',{name:'保存到本机浏览器',exact:true}).click();await page.locator('[data-action="files"]').first().click();await page.getByRole('button',{name:'恢复所选任务'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.locator('[data-action="files"]').first().click();await page.getByLabel(/导入研究 JSON/).setInputFiles(exported);await page.getByRole('dialog').waitFor({state:'hidden'});check('本机保存、恢复与 JSON 导入');
await nav('delivery');const html=await download(()=>page.getByRole('button',{name:'导出 HTML ↓',exact:true}).click(),'roundtrip-workbench.html');const exportedPage=await context.newPage();exportedPage.on('pageerror',e=>evidence.errors.push(e.message));await exportedPage.goto(pathToFileURL(html).href);await exportedPage.locator('body[data-ready="true"]').waitFor();assert.equal(await exportedPage.locator('#task-switch option').count(),1);assert.ok((await exportedPage.locator('#content').innerText()).includes('试运行包已冻结'));await exportedPage.close();check('自包含 HTML 导出后可直接打开');
await nav('home');await page.getByRole('button',{name:/新建任务/}).click();await page.getByLabel('任务 ID · 唯一编号').fill('UI-TEST-001');await page.getByLabel('想研究什么？').fill('定向验证任务');await page.getByLabel('本次研究目标').fill('仅验证 S0 创建');await page.getByLabel('核心问题 · 每行一项').fill('待研究的问题');await page.getByRole('button',{name:'校验范围并创建任务'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});for(const v of ['home','scope','evidence','review','directions','delivery'])await nav(v);assert.equal(await page.locator('#task-switch option').count(),3);check('S0 新任务创建与空数据页面');
assert.deepEqual(evidence.errors,[]);
// Fresh page for mobile layout, free of validation decisions.
const mobile=await context.newPage();mobile.on('pageerror',e=>evidence.errors.push(e.message));await mobile.setViewportSize({width:390,height:844});await mobile.goto(pathToFileURL(path.join(D,'index.html')).href);await mobile.locator('body[data-ready="true"]').waitFor();for(const v of ['home','scope','evidence','review','directions','delivery']){await mobile.locator('[data-action="menu"]').click();await mobile.locator('#nav [data-go="'+v+'"]').click();const bounds=await mobile.evaluate(()=>({vw:innerWidth,sw:document.documentElement.scrollWidth,vh:innerHeight,sh:document.documentElement.scrollHeight}));assert.ok(bounds.sw<=bounds.vw+1,JSON.stringify({v,...bounds}));assert.ok(bounds.sh<=bounds.vh+1,JSON.stringify({v,...bounds}));await mobile.getByRole('button',{name:'使用帮助',exact:true}).click();await mobile.getByRole('button',{name:'关闭使用帮助'}).click()}await mobile.locator('[data-action="menu"]').click();await mobile.locator('#nav [data-go="evidence"]').click();await mobile.screenshot({path:path.join(T,'mobile-evidence.png')});check('390px 六页面及帮助，无整页横向或无限纵向滚动');
assert.deepEqual(evidence.errors,[]);evidence.result='passed';
}catch(e){evidence.result='failed';evidence.failure=e.stack;await page.screenshot({path:path.join(T,'failure.png')});throw e}finally{fs.writeFileSync(path.join(T,'validation.json'),JSON.stringify(evidence,null,2));await browser.close()}
})();
